function varargout=F_seg2(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:16);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',12);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_seg2_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_seg2_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32)
%F_seg2_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:32:43

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.^2;
t5 = in2.^2;
t6 = -in5;
t7 = in12-1.0;
t8 = t4+t5;
t9 = sqrt(t8);
t10 = 1.0./t9;
t11 = -t9;
t12 = t9-1.0;
t13 = in1.*in2.*t10;
t14 = in5+t11;
t15 = in1.*t14;
t16 = in2.*t14;
t17 = -t15;
t18 = t2+t16;
t19 = t3+t17;
out1 = -in7.*t7.*(in2-t12.*t19);
if nargout > 1
    out2 = in7.*t7.*(in1-t12.*t18);
end
if nargout > 2
    out3 = -in3.*in7.*t7.*(t12.*(t6+t9+t4.*t10)+in1.*t10.*t19)+in4.*in7.*t7.*(t12.*(in6-t13)+in1.*t10.*t18-1.0);
end
if nargout > 3
    out4 = -in4.*in7.*t7.*(t12.*(t6+t9+t5.*t10)-in2.*t10.*t18)-in3.*in7.*t7.*(t12.*(in6+t13)+in2.*t10.*t19-1.0);
end
end


function [out1,out2,out3,out4] = F_seg2_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32)
%F_seg2_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:32:44

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in22;
t5 = in6.*in17;
t6 = in2.*in22;
t7 = in6.*in18;
t8 = in1.^2;
t9 = in2.^2;
t10 = in1.*in17.*2.0;
t11 = in2.*in18.*2.0;
t12 = -in5;
t13 = in12-1.0;
t16 = t8+t9;
t17 = t10+t11;
t18 = sqrt(t16);
t19 = 1.0./t18;
t21 = -t18;
t22 = t18-1.0;
t20 = t19.^3;
t23 = in1.*in2.*t19;
t24 = in1.*in18.*t19;
t25 = in2.*in17.*t19;
t26 = in5+t21;
t27 = t8.*t19;
t28 = t9.*t19;
t39 = (t17.*t19)./2.0;
t29 = in6+t23;
t30 = -t23;
t31 = in1.*t26;
t32 = in2.*t26;
t33 = in17.*t26;
t34 = in18.*t26;
t40 = -t39;
t41 = (in1.*in2.*t17.*t20)./2.0;
t46 = t12+t18+t27;
t47 = t12+t18+t28;
t35 = in6+t30;
t36 = -t31;
t37 = t2+t32;
t42 = in21+t40;
t45 = t22.*t29;
t60 = t22.*t46;
t61 = t22.*t47;
t38 = t3+t36;
t43 = in1.*t42;
t44 = in2.*t42;
t48 = t22.*t35;
t49 = in1.*t19.*t37;
t50 = in2.*t19.*t37;
t51 = t22.*t37;
t52 = in1.*t19.*t38;
t53 = in2.*t19.*t38;
t55 = t22.*t38;
t56 = -t51;
t62 = t4+t5+t34+t44;
t64 = t48+t49-1.0;
t57 = in1+t56;
t58 = -t55;
t65 = t45+t53-1.0;
t66 = t52+t60;
t59 = in2+t58;
out1 = in7.*t13.*(-in18+t38.*t39+t22.*(t6+t7-t33-t43))-in7.*in28.*t59-in23.*t13.*t59;
if nargout > 1
    out2 = in7.*in28.*t57+in23.*t13.*t57-in7.*t13.*(-in17+t37.*t39+t22.*t62);
end
if nargout > 2
    out3 = in4.*in7.*in28.*t64-in3.*in7.*in28.*t66+in4.*in23.*t13.*t64+in7.*in20.*t13.*t64-in3.*in23.*t13.*t66-in7.*in19.*t13.*t66-in3.*in7.*t13.*(-t22.*(t42-in1.*in17.*t19.*2.0+(t8.*t17.*t20)./2.0)+t39.*t46+in1.*t19.*(t6+t7-t33-t43)+in17.*t19.*t38-(in1.*t17.*t20.*t38)./2.0)+in4.*in7.*t13.*(t35.*t39+t22.*(in22-t24-t25+t41)+in17.*t19.*t37+in1.*t19.*t62-(in1.*t17.*t20.*t37)./2.0);
end
if nargout > 3
    out4 = -in3.*in7.*in28.*t65-in3.*in23.*t13.*t65-in7.*in19.*t13.*t65+in4.*in7.*in28.*(t50-t61)+in4.*in23.*t13.*(t50-t61)+in7.*in20.*t13.*(t50-t61)+in4.*in7.*t13.*(t22.*(t42-in2.*in18.*t19.*2.0+(t9.*t17.*t20)./2.0)+in18.*t19.*t37+in2.*t19.*t62-(t17.*t19.*t47)./2.0-(in2.*t17.*t20.*t37)./2.0)-in3.*in7.*t13.*(t29.*t39+t22.*(in22+t24+t25-t41)+in2.*t19.*(t6+t7-t33-t43)+in18.*t19.*t38-(in2.*t17.*t20.*t38)./2.0);
end
end


function [out1,out2,out3,out4] = F_seg2_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32)
%F_seg2_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:32:44

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in22;
t5 = in6.*in17;
t6 = in2.*in22;
t7 = in6.*in18;
t8 = in1.^2;
t9 = in2.^2;
t10 = in17.^2;
t11 = in18.^2;
t12 = in1.*in17.*2.0;
t13 = in2.*in18.*2.0;
t14 = in17.*in22.*2.0;
t15 = in18.*in22.*2.0;
t16 = -in5;
t17 = -in17;
t18 = in12-1.0;
t19 = t10.*2.0;
t20 = t11.*2.0;
t23 = t8+t9;
t24 = t12+t13;
t25 = t24.^2;
t26 = sqrt(t23);
t27 = t19+t20;
t28 = 1.0./t26;
t31 = -t26;
t32 = t26-1.0;
t29 = t28.^3;
t30 = t28.^5;
t33 = in1.*in2.*t28;
t34 = in1.*in18.*t28;
t35 = in2.*in17.*t28;
t36 = in5+t31;
t37 = t8.*t28;
t38 = t9.*t28;
t41 = in17.*in18.*t28.*2.0;
t44 = in1.*in17.*t28.*-2.0;
t46 = in2.*t17.*t28;
t47 = in2.*in18.*t28.*-2.0;
t59 = (t24.*t28)./2.0;
t62 = (t27.*t28)./2.0;
t42 = in6+t33;
t43 = -t33;
t45 = -t34;
t48 = -t41;
t49 = in1.*t36;
t50 = in2.*t36;
t52 = in18.*t36;
t56 = in1.*in18.*t24.*t29;
t57 = in2.*in17.*t24.*t29;
t60 = -t59;
t61 = (in1.*in2.*t24.*t29)./2.0;
t63 = (t25.*t29)./4.0;
t65 = (t8.*t24.*t29)./2.0;
t66 = (t9.*t24.*t29)./2.0;
t69 = (in1.*in2.*t27.*t29)./2.0;
t70 = in1.*in2.*t25.*t30.*(3.0./4.0);
t78 = t16+t26+t37;
t79 = t16+t26+t38;
t53 = in6+t43;
t54 = -t49;
t55 = t2+t50;
t64 = in21+t60;
t67 = -t61;
t68 = -t63;
t73 = -t70;
t77 = t32.*t42;
t91 = t42.*t59;
t93 = t32.*t78;
t94 = t32.*t79;
t107 = t59.*t78;
t112 = t24.*t28.*t79.*(-1.0./2.0);
t116 = in22+t45+t46+t61;
t58 = t3+t54;
t71 = in1.*t64;
t72 = in2.*t64;
t74 = in17.*t64.*2.0;
t75 = in18.*t64.*2.0;
t80 = t32.*t53;
t81 = in1.*t28.*t55;
t82 = in2.*t28.*t55;
t83 = in17.*t28.*t55;
t84 = in18.*t28.*t55;
t92 = t53.*t59;
t95 = t55.*t59;
t96 = (in1.*t24.*t29.*t55)./2.0;
t97 = (in2.*t24.*t29.*t55)./2.0;
t106 = t62+t68;
t114 = in22+t34+t35+t67;
t124 = t44+t64+t65;
t125 = t47+t64+t66;
t129 = t32.*t116;
t137 = t48+t56+t57+t69+t73;
t76 = -t74;
t85 = in1.*t28.*t58;
t86 = in2.*t28.*t58;
t88 = in17.*t28.*t58;
t89 = in18.*t28.*t58;
t98 = t58.*t59;
t99 = -t96;
t100 = -t97;
t102 = (in1.*t24.*t29.*t58)./2.0;
t103 = (in2.*t24.*t29.*t58)./2.0;
t105 = t4+t5+t52+t72;
t109 = in1.*t106;
t110 = in2.*t106;
t122 = t80+t81-1.0;
t127 = in2.*t28.*(t6+t7-t71+t17.*t36);
t128 = t32.*t114;
t132 = t32.*t124;
t133 = t32.*t125;
t139 = t32.*t137;
t104 = -t103;
t115 = -t110;
t117 = in1.*t28.*t105;
t118 = in2.*t28.*t105;
t119 = t32.*t105;
t123 = t77+t86-1.0;
t130 = t85+t93;
t134 = t15+t76+t109;
out1 = in7.*t18.*(t32.*t134+t24.*t28.*(t6+t7-t71+t17.*t36)-(t25.*t29.*t58)./4.0+(t27.*t28.*t58)./2.0)+in7.*in28.*(-in18+t98+t32.*(t6+t7-t71+t17.*t36)).*2.0+in23.*t18.*(-in18+t98+t32.*(t6+t7-t71+t17.*t36)).*2.0-in23.*in28.*(in2-t32.*t58).*2.0;
if nargout > 1
    t135 = t14+t75+t115;
    t136 = t17+t95+t119;
    out2 = in23.*in28.*(in1-t32.*t55).*2.0-in7.*t18.*(t55.*t62+t32.*t135-(t25.*t29.*t55)./4.0+t24.*t28.*t105)-in7.*in28.*t136.*2.0-in23.*t18.*t136.*2.0;
end
if nargout > 2
    t140 = t83+t92+t99+t117+t129;
    et1 = in4.*in23.*in28.*t122.*2.0+in7.*in20.*in28.*t122.*2.0+in4.*in7.*in28.*t140.*2.0-in3.*in23.*in28.*t130.*2.0-in7.*in19.*in28.*t130.*2.0+in20.*in23.*t18.*t122.*2.0+in4.*in23.*t18.*t140.*2.0+in7.*in20.*t18.*t140.*2.0-in19.*in23.*t18.*t130.*2.0-in3.*in7.*t18.*(t62.*t78+t32.*(t106+t19.*t28+t8.*t25.*t30.*(3.0./4.0)-(t8.*t27.*t29)./2.0-in1.*in17.*t24.*t29.*2.0)+in17.*t28.*(t6+t7-t71+t17.*t36).*2.0+in1.*t28.*t134-(t25.*t29.*t78)./4.0-t24.*t28.*t124-in1.*t24.*t29.*(t6+t7-t71+t17.*t36)+in1.*t25.*t30.*t58.*(3.0./4.0)-(in1.*t27.*t29.*t58)./2.0+t17.*t24.*t29.*t58)-in3.*in7.*in28.*(t88-t102+t107-t132+in1.*t28.*(t6+t7-t71+t17.*t36)).*2.0;
    et2 = in3.*in23.*t18.*(t88-t102+t107-t132+in1.*t28.*(t6+t7-t71+t17.*t36)).*-2.0-in7.*in19.*t18.*(t88-t102+t107-t132+in1.*t28.*(t6+t7-t71+t17.*t36)).*2.0+in4.*in7.*t18.*(t139+t53.*t62+in17.*t28.*t105.*2.0+in1.*t28.*t135-(t25.*t29.*t53)./4.0+t24.*t28.*t116+in1.*t25.*t30.*t55.*(3.0./4.0)-(in1.*t27.*t29.*t55)./2.0-in1.*t24.*t29.*t105+t17.*t24.*t29.*t55);
    out3 = et1+et2;
end
if nargout > 3
    t141 = t89+t91+t104+t127+t128;
    t142 = t84+t100+t112+t118+t133;
    et3 = in3.*in7.*t18.*(t139+t42.*t63-in18.*t28.*(t6+t7-t71+t17.*t36).*2.0-in2.*t28.*t134-(t27.*t28.*t42)./2.0-t24.*t28.*t114+in2.*t24.*t29.*(t6+t7-t71+t17.*t36)-in2.*t25.*t30.*t58.*(3.0./4.0)+(in2.*t27.*t29.*t58)./2.0+in18.*t24.*t29.*t58)-in3.*in23.*in28.*t123.*2.0-in7.*in19.*in28.*t123.*2.0-in3.*in7.*in28.*t141.*2.0+in4.*in7.*in28.*t142.*2.0-in19.*in23.*t18.*t123.*2.0-in3.*in23.*t18.*t141.*2.0-in7.*in19.*t18.*t141.*2.0+in4.*in23.*t18.*t142.*2.0+in7.*in20.*t18.*t142.*2.0;
    et4 = -in4.*in7.*t18.*(t62.*t79+t32.*(t106+t20.*t28+t9.*t25.*t30.*(3.0./4.0)-(t9.*t27.*t29)./2.0-in2.*in18.*t24.*t29.*2.0)-in18.*t28.*t105.*2.0-in2.*t28.*t135-(t25.*t29.*t79)./4.0-t24.*t28.*t125-in2.*t25.*t30.*t55.*(3.0./4.0)+(in2.*t27.*t29.*t55)./2.0+in18.*t24.*t29.*t55+in2.*t24.*t29.*t105)+in4.*in23.*in28.*(t82-t94).*2.0+in7.*in20.*in28.*(t82-t94).*2.0+in20.*in23.*t18.*(t82-t94).*2.0;
    out4 = et3+et4;
end
end

