function varargout=F_seg3(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('x',1:2,'p',3:14);
   return
  case 'argsize'
   varargout{1}=struct('x',2,'p',12);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('F_seg3_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = F_seg3_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%F_seg3_rhs_0
%    [OUT1,OUT2] = F_seg3_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:32:45

t2 = in1.^2;
t3 = in2.^2;
t4 = in9-1.0;
t5 = t2+t3;
t6 = sqrt(t5);
t7 = -t6;
t8 = t6-1.0;
t9 = in3+t7;
out1 = -in5.*t4.*(in2-t8.*(in2.*in4-in1.*t9));
if nargout > 1
    out2 = in5.*t4.*(in1-t8.*(in1.*in4+in2.*t9));
end
end


function [out1,out2] = F_seg3_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%F_seg3_rhs_1
%    [OUT1,OUT2] = F_seg3_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:32:45

t2 = in1.*in4;
t3 = in2.*in4;
t4 = in1.^2;
t5 = in2.^2;
t6 = in1.*in15.*2.0;
t7 = in2.*in16.*2.0;
t8 = in9-1.0;
t9 = t4+t5;
t10 = t6+t7;
t11 = sqrt(t9);
t12 = 1.0./t11;
t13 = -t11;
t14 = t11-1.0;
t15 = in3+t13;
t21 = (t10.*t12)./2.0;
t16 = in1.*t15;
t17 = in2.*t15;
t22 = -t21;
t18 = -t16;
t19 = t2+t17;
t23 = in17+t22;
t20 = t3+t18;
t24 = t14.*t19;
t25 = t14.*t20;
t26 = -t24;
t27 = in1+t26;
t28 = -t25;
t29 = in2+t28;
out1 = -in5.*in23.*t29-in19.*t8.*t29+in5.*t8.*(-in16+t14.*(in2.*in18+in4.*in16-in1.*t23-in15.*t15)+t20.*t21);
if nargout > 1
    out2 = in5.*in23.*t27+in19.*t8.*t27-in5.*t8.*(-in15+t14.*(in1.*in18+in4.*in15+in2.*t23+in16.*t15)+t19.*t21);
end
end


function [out1,out2] = F_seg3_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%F_seg3_rhs_2
%    [OUT1,OUT2] = F_seg3_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:32:46

t2 = in1.*in4;
t3 = in2.*in4;
t4 = in1.*in18;
t5 = in4.*in15;
t6 = in2.*in18;
t7 = in4.*in16;
t8 = in1.^2;
t9 = in2.^2;
t10 = in15.^2;
t11 = in16.^2;
t12 = in1.*in15.*2.0;
t13 = in2.*in16.*2.0;
t14 = -in15;
t15 = in9-1.0;
t16 = t10.*2.0;
t17 = t11.*2.0;
t20 = t8+t9;
t21 = t12+t13;
t22 = t21.^2;
t23 = sqrt(t20);
t24 = t16+t17;
t25 = 1.0./t23;
t27 = -t23;
t28 = t23-1.0;
t26 = t25.^3;
t29 = in3+t27;
t37 = (t21.*t25)./2.0;
t39 = (t24.*t25)./2.0;
t30 = in1.*t29;
t31 = in2.*t29;
t33 = in16.*t29;
t38 = -t37;
t40 = (t22.*t26)./4.0;
t34 = -t30;
t35 = t2+t31;
t41 = in17+t38;
t42 = -t40;
t36 = t3+t34;
t43 = in1.*t41;
t44 = in2.*t41;
t45 = t35.*t37;
t49 = t39+t42;
t46 = t36.*t37;
out1 = in5.*in23.*(-in16+t46+t28.*(t6+t7-t43+t14.*t29)).*2.0+in19.*t15.*(-in16+t46+t28.*(t6+t7-t43+t14.*t29)).*2.0-in19.*in23.*(in2-t28.*t36).*2.0+in5.*t15.*(t28.*(in16.*in18.*2.0+in1.*t49-in15.*t41.*2.0)+t21.*t25.*(t6+t7-t43+t14.*t29)-(t22.*t26.*t36)./4.0+(t24.*t25.*t36)./2.0);
if nargout > 1
    t48 = t4+t5+t33+t44;
    t51 = t28.*t48;
    t53 = t14+t45+t51;
    out2 = -in5.*t15.*(t35.*t39+t28.*(in15.*in18.*2.0-in2.*t49+in16.*t41.*2.0)-(t22.*t26.*t35)./4.0+t21.*t25.*t48)+in19.*in23.*(in1-t28.*t35).*2.0-in5.*in23.*t53.*2.0-in19.*t15.*t53.*2.0;
end
end

