function varargout=F_bcs_seg1_seg2(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=10;
   return
  case 'argrange'
   varargout{1}=struct('u',1:28);
   return
  case 'argsize'
   varargout{1}=struct('u',28);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=10;
order=varargin{1};
f=str2func(sprintf('F_bcs_seg1_seg2_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10] = F_bcs_seg1_seg2_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56)
%F_bcs_seg1_seg2_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10] = F_bcs_seg1_seg2_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:33:47

out1 = in1-in13;
if nargout > 1
    out2 = in2-in14;
end
if nargout > 2
    out3 = -in5+in9;
end
if nargout > 3
    out4 = -in6+in10;
end
if nargout > 4
    t2 = in1.^2;
    t3 = in2.^2;
    t4 = t2+t3;
    t5 = sqrt(t4);
    out5 = in2-(t5-1.0).*(in2.*in18-in1.*(in17-t5));
end
if nargout > 5
    out6 = in3-in15;
end
if nargout > 6
    out7 = in4-in16;
end
if nargout > 7
    out8 = -in11+in7.*in21;
end
if nargout > 8
    out9 = -in12+in8.*in21;
end
if nargout > 9
    out10 = sqrt(abs(in7).^2+abs(in8).^2)-1.0;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10] = F_bcs_seg1_seg2_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56)
%F_bcs_seg1_seg2_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10] = F_bcs_seg1_seg2_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:33:47

out1 = in29-in41;
if nargout > 1
    out2 = in30-in42;
end
if nargout > 2
    out3 = -in33+in37;
end
if nargout > 3
    out4 = -in34+in38;
end
if nargout > 4
    t2 = abs(in7);
    t3 = abs(in8);
    t4 = conj(in7);
    t5 = conj(in8);
    t6 = in1.^2;
    t7 = in2.^2;
    t8 = in1.*in29.*2.0;
    t9 = in2.*in30.*2.0;
    t10 = t6+t7;
    t11 = t8+t9;
    t12 = sqrt(t10);
    t13 = 1.0./t12;
    t14 = -t12;
    t15 = in17+t14;
    out5 = in30-(t12-1.0).*(in2.*in46+in18.*in30-in29.*t15-in1.*(in45-(t11.*t13)./2.0))-(t11.*t13.*(in2.*in18-in1.*t15))./2.0;
end
if nargout > 5
    out6 = in31-in43;
end
if nargout > 6
    out7 = in32-in44;
end
if nargout > 7
    out8 = -in39+in7.*in49+in21.*in35;
end
if nargout > 8
    out9 = -in40+in8.*in49+in21.*in36;
end
if nargout > 9
    out10 = (1.0./sqrt(t2.^2+t3.^2).*(t2.*(in35.*t4+in7.*conj(in35)).*1.0./sqrt(in7.*t4)+t3.*(in36.*t5+in8.*conj(in36)).*1.0./sqrt(in8.*t5)))./2.0;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10] = F_bcs_seg1_seg2_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56)
%F_bcs_seg1_seg2_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10] = F_bcs_seg1_seg2_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-May-2024 11:33:47

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    t2 = abs(in7);
    t3 = abs(in8);
    t4 = conj(in7);
    t5 = conj(in8);
    t6 = conj(in35);
    t7 = conj(in36);
    t8 = in2.*in18;
    t9 = in1.^2;
    t10 = in2.^2;
    t11 = in29.^2;
    t12 = in30.^2;
    t15 = in1.*in29.*2.0;
    t16 = in2.*in30.*2.0;
    t13 = t2.^2;
    t14 = t3.^2;
    t17 = in7.*t4;
    t18 = in8.*t5;
    t19 = in7.*t6;
    t20 = in35.*t4;
    t21 = in8.*t7;
    t22 = in36.*t5;
    t23 = t11.*2.0;
    t24 = t12.*2.0;
    t25 = t9+t10;
    t29 = t15+t16;
    t26 = t19+t20;
    t27 = t21+t22;
    t28 = t13+t14;
    t30 = 1.0./sqrt(t17);
    t31 = 1.0./sqrt(t18);
    t32 = t29.^2;
    t33 = sqrt(t25);
    t34 = t23+t24;
    t35 = t26.^2;
    t36 = t27.^2;
    t37 = 1.0./t33;
    t39 = -t33;
    t38 = t37.^3;
    t40 = in17+t39;
    t44 = (t29.*t37)./2.0;
    t41 = in1.*t40;
    t45 = -t44;
    t42 = -t41;
    t46 = in45+t45;
    t43 = t8+t42;
    out5 = (t33-1.0).*(in30.*in46.*-2.0+in29.*t46.*2.0+in1.*((t32.*t38)./4.0-(t34.*t37)./2.0))-t29.*t37.*(in2.*in46+in18.*in30-in1.*t46-in29.*t40)+(t32.*t38.*t43)./4.0-(t34.*t37.*t43)./2.0;
end
if nargout > 5
    out6 = 0.0;
end
if nargout > 6
    out7 = 0.0;
end
if nargout > 7
    out8 = in35.*in49.*2.0;
end
if nargout > 8
    out9 = in36.*in49.*2.0;
end
if nargout > 9
    out10 = (1.0./sqrt(t28).*((t30.^2.*t35)./2.0+(t31.^2.*t36)./2.0-(t2.*t30.^3.*t35)./2.0-(t3.*t31.^3.*t36)./2.0+in35.*t2.*t6.*t30.*2.0+in36.*t3.*t7.*t31.*2.0))./2.0-(1.0./t28.^(3.0./2.0).*(t2.*t26.*t30+t3.*t27.*t31).^2)./4.0;
end
end

