function varargout=F_bcs_seg1_seg2(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=10;
   return
  case 'argrange'
   varargout{1}=struct('u',1:29);
   return
  case 'argsize'
   varargout{1}=struct('u',29);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=10;
order=varargin{1};
f=str2func(sprintf('F_bcs_seg1_seg2_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10] = F_bcs_seg1_seg2_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58)
%F_bcs_seg1_seg2_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10] = F_bcs_seg1_seg2_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Jan-2024 08:58:26

out1 = in1-in13;
if nargout > 1
    out2 = in2-in14;
end
if nargout > 2
    out3 = -in5+in9;
end
if nargout > 3
    out4 = -in6+in10;
end
if nargout > 4
    out5 = in17.*(in1+in2+in20-in1.^3./3.0);
end
if nargout > 5
    out6 = in3-in15;
end
if nargout > 6
    out7 = in4-in16;
end
if nargout > 7
    out8 = -in11+in7.*in22;
end
if nargout > 8
    out9 = -in12+in8.*in22;
end
if nargout > 9
    out10 = sqrt(abs(in7).^2+abs(in8).^2)-1.0;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10] = F_bcs_seg1_seg2_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58)
%F_bcs_seg1_seg2_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10] = F_bcs_seg1_seg2_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Jan-2024 08:58:26

out1 = in30-in42;
if nargout > 1
    out2 = in31-in43;
end
if nargout > 2
    out3 = -in34+in38;
end
if nargout > 3
    out4 = -in35+in39;
end
if nargout > 4
    out5 = in46.*(in1+in2+in20-in1.^3./3.0)+in17.*(in30+in31+in49-in1.^2.*in30);
end
if nargout > 5
    out6 = in32-in44;
end
if nargout > 6
    out7 = in33-in45;
end
if nargout > 7
    out8 = -in40+in7.*in51+in22.*in36;
end
if nargout > 8
    out9 = -in41+in8.*in51+in22.*in37;
end
if nargout > 9
    t2 = abs(in7);
    t3 = abs(in8);
    t4 = conj(in7);
    t5 = conj(in8);
    out10 = (1.0./sqrt(t2.^2+t3.^2).*(t2.*(in36.*t4+in7.*conj(in36)).*1.0./sqrt(in7.*t4)+t3.*(in37.*t5+in8.*conj(in37)).*1.0./sqrt(in8.*t5)))./2.0;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10] = F_bcs_seg1_seg2_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58)
%F_bcs_seg1_seg2_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10] = F_bcs_seg1_seg2_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Jan-2024 08:58:26

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    out5 = in46.*(in30+in31+in49-in1.^2.*in30).*2.0-in1.*in17.*in30.^2.*2.0;
end
if nargout > 5
    out6 = 0.0;
end
if nargout > 6
    out7 = 0.0;
end
if nargout > 7
    out8 = in36.*in51.*2.0;
end
if nargout > 8
    out9 = in37.*in51.*2.0;
end
if nargout > 9
    t2 = abs(in7);
    t3 = abs(in8);
    t4 = conj(in7);
    t5 = conj(in8);
    t6 = conj(in36);
    t7 = conj(in37);
    t8 = t2.^2;
    t9 = t3.^2;
    t10 = in7.*t4;
    t11 = in8.*t5;
    t12 = in7.*t6;
    t13 = in36.*t4;
    t14 = in8.*t7;
    t15 = in37.*t5;
    t16 = t12+t13;
    t17 = t14+t15;
    t18 = t8+t9;
    t19 = 1.0./sqrt(t10);
    t20 = 1.0./sqrt(t11);
    t21 = t16.^2;
    t22 = t17.^2;
    out10 = (1.0./sqrt(t18).*((t19.^2.*t21)./2.0+(t20.^2.*t22)./2.0-(t2.*t19.^3.*t21)./2.0-(t3.*t20.^3.*t22)./2.0+in36.*t2.*t6.*t19.*2.0+in37.*t3.*t7.*t20.*2.0))./2.0-(1.0./t18.^(3.0./2.0).*(t2.*t16.*t19+t3.*t17.*t20).^2)./4.0;
end
end

