function varargout=F_bcs_seg3(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('u',1:4);
   return
  case 'argsize'
   varargout{1}=struct('u',4);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('F_bcs_seg3_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = F_bcs_seg3_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8)
%F_bcs_seg3_rhs_0
%    [OUT1,OUT2] = F_bcs_seg3_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Jan-2024 08:58:26

out1 = -in1+in3;
if nargout > 1
    out2 = -in2+in4;
end
end


function [out1,out2] = F_bcs_seg3_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8)
%F_bcs_seg3_rhs_1
%    [OUT1,OUT2] = F_bcs_seg3_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Jan-2024 08:58:26

out1 = -in5+in7;
if nargout > 1
    out2 = -in6+in8;
end
end


function [out1,out2] = F_bcs_seg3_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8)
%F_bcs_seg3_rhs_2
%    [OUT1,OUT2] = F_bcs_seg3_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Jan-2024 08:58:26

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
end

