function varargout=F_bcs_PR_segs(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=22;
   return
  case 'argrange'
   varargout{1}=struct('u',1:49);
   return
  case 'argsize'
   varargout{1}=struct('u',49);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=22;
order=varargin{1};
f=str2func(sprintf('F_bcs_PR_segs_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10,out11,out12,out13,out14,out15,out16,out17,out18,out19,out20,out21,out22] = F_bcs_PR_segs_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58,in59,in60,in61,in62,in63,in64,in65,in66,in67,in68,in69,in70,in71,in72,in73,in74,in75,in76,in77,in78,in79,in80,in81,in82,in83,in84,in85,in86,in87,in88,in89,in90,in91,in92,in93,in94,in95,in96,in97,in98)
%F_bcs_PR_segs_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15,OUT16,OUT17,OUT18,OUT19,OUT20,OUT21,OUT22] = F_bcs_PR_segs_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58,IN59,IN60,IN61,IN62,IN63,IN64,IN65,IN66,IN67,IN68,IN69,IN70,IN71,IN72,IN73,IN74,IN75,IN76,IN77,IN78,IN79,IN80,IN81,IN82,IN83,IN84,IN85,IN86,IN87,IN88,IN89,IN90,IN91,IN92,IN93,IN94,IN95,IN96,IN97,IN98)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Jul-2024 17:28:03

out1 = in1-in25;
if nargout > 1
    out2 = in2-in26;
end
if nargout > 2
    out3 = in3-in27;
end
if nargout > 3
    out4 = in7-in19;
end
if nargout > 4
    out5 = in8-in20;
end
if nargout > 5
    out6 = in9-in21;
end
if nargout > 6
    out7 = -in37.*(in1-in38+in1.*in3);
end
if nargout > 7
    out8 = -in10+in22;
end
if nargout > 8
    out9 = -in11+in23;
end
if nargout > 9
    out10 = -in12+in24;
end
if nargout > 10
    out11 = -in28+in4.*in45;
end
if nargout > 11
    out12 = -in29+in5.*in45;
end
if nargout > 12
    out13 = -in30+in6.*in45;
end
if nargout > 13
    out14 = sqrt(abs(in28).^2+abs(in29).^2+abs(in30).^2)-1.0;
end
if nargout > 14
    out15 = -in1+in31;
end
if nargout > 15
    out16 = -in2+in32;
end
if nargout > 16
    out17 = -in3+in33;
end
if nargout > 17
    out18 = -in13+in16-in47.*cos(in48);
end
if nargout > 18
    out19 = -in14+in17;
end
if nargout > 19
    out20 = -in15+in18-in47.*sin(in48);
end
if nargout > 20
    t2 = -in34;
    t3 = -in35;
    t4 = -in36;
    t5 = in7+t2;
    t6 = in8+t3;
    t7 = in9+t4;
    out21 = -in10.*t5-in11.*t6-in12.*t7;
end
if nargout > 21
    out22 = -in46+t5.^2+t6.^2+t7.^2;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10,out11,out12,out13,out14,out15,out16,out17,out18,out19,out20,out21,out22] = F_bcs_PR_segs_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58,in59,in60,in61,in62,in63,in64,in65,in66,in67,in68,in69,in70,in71,in72,in73,in74,in75,in76,in77,in78,in79,in80,in81,in82,in83,in84,in85,in86,in87,in88,in89,in90,in91,in92,in93,in94,in95,in96,in97,in98)
%F_bcs_PR_segs_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15,OUT16,OUT17,OUT18,OUT19,OUT20,OUT21,OUT22] = F_bcs_PR_segs_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58,IN59,IN60,IN61,IN62,IN63,IN64,IN65,IN66,IN67,IN68,IN69,IN70,IN71,IN72,IN73,IN74,IN75,IN76,IN77,IN78,IN79,IN80,IN81,IN82,IN83,IN84,IN85,IN86,IN87,IN88,IN89,IN90,IN91,IN92,IN93,IN94,IN95,IN96,IN97,IN98)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Jul-2024 17:28:04

out1 = in50-in74;
if nargout > 1
    out2 = in51-in75;
end
if nargout > 2
    out3 = in52-in76;
end
if nargout > 3
    out4 = in56-in68;
end
if nargout > 4
    out5 = in57-in69;
end
if nargout > 5
    out6 = in58-in70;
end
if nargout > 6
    out7 = -in86.*(in1-in38+in1.*in3)-in37.*(in50-in87+in1.*in52+in3.*in50);
end
if nargout > 7
    out8 = -in59+in71;
end
if nargout > 8
    out9 = -in60+in72;
end
if nargout > 9
    out10 = -in61+in73;
end
if nargout > 10
    out11 = -in77+in4.*in94+in45.*in53;
end
if nargout > 11
    out12 = -in78+in5.*in94+in45.*in54;
end
if nargout > 12
    out13 = -in79+in6.*in94+in45.*in55;
end
if nargout > 13
    t2 = abs(in28);
    t3 = abs(in29);
    t4 = abs(in30);
    out14 = ((t2.*(in28.*in77+in28.*conj(in77)).*1.0./sqrt(in28.^2)+t3.*(in29.*in78+in29.*conj(in78)).*1.0./sqrt(in29.^2)+t4.*(in30.*in79+in30.*conj(in79)).*1.0./sqrt(in30.^2)).*1.0./sqrt(t2.^2+t3.^2+t4.^2))./2.0;
end
if nargout > 14
    out15 = -in50+in80;
end
if nargout > 15
    out16 = -in51+in81;
end
if nargout > 16
    out17 = -in52+in82;
end
if nargout > 17
    t5 = cos(in48);
    t6 = sin(in48);
    out18 = -in62+in65-in96.*t5+in47.*in97.*t6;
end
if nargout > 18
    out19 = -in63+in66;
end
if nargout > 19
    out20 = -in64+in67-in96.*t6-in47.*in97.*t5;
end
if nargout > 20
    t7 = -in34;
    t8 = -in35;
    t9 = -in36;
    t10 = -in83;
    t11 = -in84;
    t12 = -in85;
    t13 = in7+t7;
    t14 = in8+t8;
    t15 = in9+t9;
    t16 = in56+t10;
    t17 = in57+t11;
    t18 = in58+t12;
    out21 = -in10.*t16-in11.*t17-in12.*t18-in59.*t13-in60.*t14-in61.*t15;
end
if nargout > 21
    out22 = -in95+t13.*t16.*2.0+t14.*t17.*2.0+t15.*t18.*2.0;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10,out11,out12,out13,out14,out15,out16,out17,out18,out19,out20,out21,out22] = F_bcs_PR_segs_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58,in59,in60,in61,in62,in63,in64,in65,in66,in67,in68,in69,in70,in71,in72,in73,in74,in75,in76,in77,in78,in79,in80,in81,in82,in83,in84,in85,in86,in87,in88,in89,in90,in91,in92,in93,in94,in95,in96,in97,in98)
%F_bcs_PR_segs_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15,OUT16,OUT17,OUT18,OUT19,OUT20,OUT21,OUT22] = F_bcs_PR_segs_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58,IN59,IN60,IN61,IN62,IN63,IN64,IN65,IN66,IN67,IN68,IN69,IN70,IN71,IN72,IN73,IN74,IN75,IN76,IN77,IN78,IN79,IN80,IN81,IN82,IN83,IN84,IN85,IN86,IN87,IN88,IN89,IN90,IN91,IN92,IN93,IN94,IN95,IN96,IN97,IN98)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Jul-2024 17:28:04

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    out5 = 0.0;
end
if nargout > 5
    out6 = 0.0;
end
if nargout > 6
    out7 = in86.*(in50-in87+in1.*in52+in3.*in50).*-2.0-in37.*in50.*in52.*2.0;
end
if nargout > 7
    out8 = 0.0;
end
if nargout > 8
    out9 = 0.0;
end
if nargout > 9
    out10 = 0.0;
end
if nargout > 10
    out11 = in53.*in94.*2.0;
end
if nargout > 11
    out12 = in54.*in94.*2.0;
end
if nargout > 12
    out13 = in55.*in94.*2.0;
end
if nargout > 13
    t2 = abs(in28);
    t3 = abs(in29);
    t4 = abs(in30);
    t5 = conj(in77);
    t6 = conj(in78);
    t7 = conj(in79);
    t8 = cos(in48);
    t9 = sin(in48);
    t10 = in28.*in77;
    t11 = in29.*in78;
    t12 = in30.*in79;
    t13 = in28.^2;
    t14 = in29.^2;
    t15 = in30.^2;
    t16 = in97.^2;
    t23 = -in83;
    t24 = -in84;
    t25 = -in85;
    t17 = t2.^2;
    t18 = t3.^2;
    t19 = t4.^2;
    t20 = in28.*t5;
    t21 = in29.*t6;
    t22 = in30.*t7;
    t26 = in56+t23;
    t27 = in57+t24;
    t28 = in58+t25;
    t32 = 1.0./sqrt(t13);
    t33 = 1.0./sqrt(t14);
    t34 = 1.0./sqrt(t15);
    t29 = t10+t20;
    t30 = t11+t21;
    t31 = t12+t22;
    t38 = t17+t18+t19;
    t35 = t29.^2;
    t36 = t30.^2;
    t37 = t31.^2;
    out14 = 1.0./t38.^(3.0./2.0).*(t2.*t29.*t32+t3.*t30.*t33+t4.*t31.*t34).^2.*(-1.0./4.0)+(1.0./sqrt(t38).*((t32.^2.*t35)./2.0+(t33.^2.*t36)./2.0+(t34.^2.*t37)./2.0-(t2.*t32.^3.*t35)./2.0-(t3.*t33.^3.*t36)./2.0-(t4.*t34.^3.*t37)./2.0+in77.*t2.*t5.*t32.*2.0+in78.*t3.*t6.*t33.*2.0+in79.*t4.*t7.*t34.*2.0))./2.0;
end
if nargout > 14
    out15 = 0.0;
end
if nargout > 15
    out16 = 0.0;
end
if nargout > 16
    out17 = 0.0;
end
if nargout > 17
    out18 = in96.*in97.*t9.*2.0+in47.*t8.*t16;
end
if nargout > 18
    out19 = 0.0;
end
if nargout > 19
    out20 = in96.*in97.*t8.*-2.0+in47.*t9.*t16;
end
if nargout > 20
    out21 = in59.*t26.*-2.0-in60.*t27.*2.0-in61.*t28.*2.0;
end
if nargout > 21
    out22 = t26.^2.*2.0+t27.^2.*2.0+t28.^2.*2.0;
end
end

