function varargout=F_bcs_PO(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('u',1:6);
   return
  case 'argsize'
   varargout{1}=struct('u',6);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('F_bcs_PO_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = F_bcs_PO_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_bcs_PO_rhs_0
%    [OUT1,OUT2,OUT3] = F_bcs_PO_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-Oct-2025 15:04:21

out1 = in1-in3;
if nargout > 1
    out2 = in2-in4;
end
if nargout > 2
    t2 = in1.^2;
    t3 = in2.^2;
    t4 = t2+t3;
    t5 = sqrt(t4);
    out3 = in2-(t5-1.0).*(in2.*in6-in1.*(in5-t5));
end
end


function [out1,out2,out3] = F_bcs_PO_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_bcs_PO_rhs_1
%    [OUT1,OUT2,OUT3] = F_bcs_PO_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-Oct-2025 15:04:21

out1 = in7-in9;
if nargout > 1
    out2 = in8-in10;
end
if nargout > 2
    t2 = in1.^2;
    t3 = in2.^2;
    t4 = in1.*in7.*2.0;
    t5 = in2.*in8.*2.0;
    t6 = t2+t3;
    t7 = t4+t5;
    t8 = sqrt(t6);
    t9 = 1.0./t8;
    t10 = -t8;
    t11 = in5+t10;
    out3 = in8-(t8-1.0).*(in2.*in12+in6.*in8-in7.*t11-in1.*(in11-(t7.*t9)./2.0))-(t7.*t9.*(in2.*in6-in1.*t11))./2.0;
end
end


function [out1,out2,out3] = F_bcs_PO_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_bcs_PO_rhs_2
%    [OUT1,OUT2,OUT3] = F_bcs_PO_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-Oct-2025 15:04:21

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    t2 = in2.*in6;
    t3 = in1.^2;
    t4 = in2.^2;
    t5 = in7.^2;
    t6 = in8.^2;
    t7 = in1.*in7.*2.0;
    t8 = in2.*in8.*2.0;
    t9 = t5.*2.0;
    t10 = t6.*2.0;
    t11 = t3+t4;
    t12 = t7+t8;
    t13 = t12.^2;
    t14 = sqrt(t11);
    t15 = t9+t10;
    t16 = 1.0./t14;
    t18 = -t14;
    t17 = t16.^3;
    t19 = in5+t18;
    t23 = (t12.*t16)./2.0;
    t20 = in1.*t19;
    t24 = -t23;
    t21 = -t20;
    t25 = in11+t24;
    t22 = t2+t21;
    out3 = (t14-1.0).*(in8.*in12.*-2.0+in7.*t25.*2.0+in1.*((t13.*t17)./4.0-(t15.*t16)./2.0))-t12.*t16.*(in2.*in12+in6.*in8-in1.*t25-in7.*t19)+(t13.*t17.*t22)./4.0-(t15.*t16.*t22)./2.0;
end
end

