function varargout=F_bcs_VAR(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('u',1:6);
   return
  case 'argsize'
   varargout{1}=struct('u',6);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('F_bcs_VAR_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = F_bcs_VAR_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_bcs_VAR_rhs_0
%    [OUT1,OUT2,OUT3] = F_bcs_VAR_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:02

out1 = in3-in1.*in5;
if nargout > 1
    out2 = in4-in2.*in5;
end
if nargout > 2
    out3 = -in6+in1.*conj(in1)+in2.*conj(in2);
end
end


function [out1,out2,out3] = F_bcs_VAR_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_bcs_VAR_rhs_1
%    [OUT1,OUT2,OUT3] = F_bcs_VAR_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:02

out1 = in9-in1.*in11-in5.*in7;
if nargout > 1
    out2 = in10-in2.*in11-in5.*in8;
end
if nargout > 2
    out3 = -in12+in1.*conj(in7)+in7.*conj(in1)+in2.*conj(in8)+in8.*conj(in2);
end
end


function [out1,out2,out3] = F_bcs_VAR_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_bcs_VAR_rhs_2
%    [OUT1,OUT2,OUT3] = F_bcs_VAR_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:02

out1 = in7.*in11.*-2.0;
if nargout > 1
    out2 = in8.*in11.*-2.0;
end
if nargout > 2
    out3 = in7.*conj(in7).*2.0+in8.*conj(in8).*2.0;
end
end

