function varargout=F_seg1(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:14);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',10);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_seg1_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_seg1_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%F_seg1_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Mar-2025 14:58:59

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.^2;
t5 = in2.^2;
t6 = -in5;
t7 = t4+t5;
t8 = sqrt(t7);
t9 = 1.0./t8;
t10 = -t8;
t11 = t8-1.0;
t12 = in1.*in2.*t9;
t13 = in5+t10;
t14 = in1.*t13;
t15 = in2.*t13;
t16 = -t14;
t17 = t2+t15;
t18 = t3+t16;
out1 = in7.*in10.*(in2-t11.*t18);
if nargout > 1
    out2 = -in7.*in10.*(in1-t11.*t17);
end
if nargout > 2
    out3 = in3.*in7.*in10.*(t11.*(t6+t8+t4.*t9)+in1.*t9.*t18)-in4.*in7.*in10.*(t11.*(in6-t12)+in1.*t9.*t17-1.0);
end
if nargout > 3
    out4 = in4.*in7.*in10.*(t11.*(t6+t8+t5.*t9)-in2.*t9.*t17)+in3.*in7.*in10.*(t11.*(in6+t12)+in2.*t9.*t18-1.0);
end
end


function [out1,out2,out3,out4] = F_seg1_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%F_seg1_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Mar-2025 14:58:59

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in20;
t5 = in6.*in15;
t6 = in2.*in20;
t7 = in6.*in16;
t8 = in1.^2;
t9 = in2.^2;
t10 = in1.*in15.*2.0;
t11 = in2.*in16.*2.0;
t12 = -in5;
t15 = t8+t9;
t16 = t10+t11;
t17 = sqrt(t15);
t18 = 1.0./t17;
t20 = -t17;
t21 = t17-1.0;
t19 = t18.^3;
t22 = in1.*in2.*t18;
t23 = in1.*in16.*t18;
t24 = in2.*in15.*t18;
t25 = in5+t20;
t26 = t8.*t18;
t27 = t9.*t18;
t38 = (t16.*t18)./2.0;
t28 = in6+t22;
t29 = -t22;
t30 = in1.*t25;
t31 = in2.*t25;
t32 = in15.*t25;
t33 = in16.*t25;
t39 = -t38;
t40 = (in1.*in2.*t16.*t19)./2.0;
t45 = t12+t17+t26;
t46 = t12+t17+t27;
t34 = in6+t29;
t35 = -t30;
t36 = t2+t31;
t41 = in19+t39;
t44 = t21.*t28;
t59 = t21.*t45;
t60 = t21.*t46;
t37 = t3+t35;
t42 = in1.*t41;
t43 = in2.*t41;
t47 = t21.*t34;
t48 = in1.*t18.*t36;
t49 = in2.*t18.*t36;
t50 = t21.*t36;
t51 = in1.*t18.*t37;
t52 = in2.*t18.*t37;
t54 = t21.*t37;
t55 = -t50;
t61 = t4+t5+t33+t43;
t63 = t47+t48-1.0;
t56 = in1+t55;
t57 = -t54;
t64 = t44+t52-1.0;
t65 = t51+t59;
t58 = in2+t57;
out1 = -in7.*in10.*(-in16+t37.*t38+t21.*(t6+t7-t32-t42))+in7.*in24.*t58+in10.*in21.*t58;
if nargout > 1
    out2 = -in7.*in24.*t56-in10.*in21.*t56+in7.*in10.*(-in15+t36.*t38+t21.*t61);
end
if nargout > 2
    out3 = -in4.*in7.*in24.*t63-in4.*in10.*in21.*t63-in7.*in10.*in18.*t63+in3.*in7.*in24.*t65+in3.*in10.*in21.*t65+in7.*in10.*in17.*t65+in3.*in7.*in10.*(-t21.*(t41-in1.*in15.*t18.*2.0+(t8.*t16.*t19)./2.0)+t38.*t45+in1.*t18.*(t6+t7-t32-t42)+in15.*t18.*t37-(in1.*t16.*t19.*t37)./2.0)-in4.*in7.*in10.*(t34.*t38+t21.*(in20-t23-t24+t40)+in15.*t18.*t36+in1.*t18.*t61-(in1.*t16.*t19.*t36)./2.0);
end
if nargout > 3
    out4 = in3.*in7.*in24.*t64+in3.*in10.*in21.*t64+in7.*in10.*in17.*t64-in4.*in7.*in24.*(t49-t60)-in4.*in10.*in21.*(t49-t60)-in7.*in10.*in18.*(t49-t60)-in4.*in7.*in10.*(t21.*(t41-in2.*in16.*t18.*2.0+(t9.*t16.*t19)./2.0)+in16.*t18.*t36+in2.*t18.*t61-(t16.*t18.*t46)./2.0-(in2.*t16.*t19.*t36)./2.0)+in3.*in7.*in10.*(t28.*t38+t21.*(in20+t23+t24-t40)+in2.*t18.*(t6+t7-t32-t42)+in16.*t18.*t37-(in2.*t16.*t19.*t37)./2.0);
end
end


function [out1,out2,out3,out4] = F_seg1_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%F_seg1_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Mar-2025 14:58:59

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in20;
t5 = in6.*in15;
t6 = in2.*in20;
t7 = in6.*in16;
t8 = in1.^2;
t9 = in2.^2;
t10 = in15.^2;
t11 = in16.^2;
t12 = in1.*in15.*2.0;
t13 = in2.*in16.*2.0;
t14 = in15.*in20.*2.0;
t15 = in16.*in20.*2.0;
t16 = -in5;
t17 = -in15;
t18 = t10.*2.0;
t19 = t11.*2.0;
t22 = t8+t9;
t23 = t12+t13;
t24 = t23.^2;
t25 = sqrt(t22);
t26 = t18+t19;
t27 = 1.0./t25;
t30 = -t25;
t31 = t25-1.0;
t28 = t27.^3;
t29 = t27.^5;
t32 = in1.*in2.*t27;
t33 = in1.*in16.*t27;
t34 = in2.*in15.*t27;
t35 = in5+t30;
t36 = t8.*t27;
t37 = t9.*t27;
t40 = in15.*in16.*t27.*2.0;
t43 = in1.*in15.*t27.*-2.0;
t45 = in2.*t17.*t27;
t46 = in2.*in16.*t27.*-2.0;
t58 = (t23.*t27)./2.0;
t61 = (t26.*t27)./2.0;
t41 = in6+t32;
t42 = -t32;
t44 = -t33;
t47 = -t40;
t48 = in1.*t35;
t49 = in2.*t35;
t51 = in16.*t35;
t55 = in1.*in16.*t23.*t28;
t56 = in2.*in15.*t23.*t28;
t59 = -t58;
t60 = (in1.*in2.*t23.*t28)./2.0;
t62 = (t24.*t28)./4.0;
t64 = (t8.*t23.*t28)./2.0;
t65 = (t9.*t23.*t28)./2.0;
t68 = (in1.*in2.*t26.*t28)./2.0;
t69 = in1.*in2.*t24.*t29.*(3.0./4.0);
t77 = t16+t25+t36;
t78 = t16+t25+t37;
t52 = in6+t42;
t53 = -t48;
t54 = t2+t49;
t63 = in19+t59;
t66 = -t60;
t67 = -t62;
t72 = -t69;
t76 = t31.*t41;
t90 = t41.*t58;
t92 = t31.*t77;
t93 = t31.*t78;
t106 = t58.*t77;
t111 = t23.*t27.*t78.*(-1.0./2.0);
t115 = in20+t44+t45+t60;
t57 = t3+t53;
t70 = in1.*t63;
t71 = in2.*t63;
t73 = in15.*t63.*2.0;
t74 = in16.*t63.*2.0;
t79 = t31.*t52;
t80 = in1.*t27.*t54;
t81 = in2.*t27.*t54;
t82 = in15.*t27.*t54;
t83 = in16.*t27.*t54;
t91 = t52.*t58;
t94 = t54.*t58;
t95 = (in1.*t23.*t28.*t54)./2.0;
t96 = (in2.*t23.*t28.*t54)./2.0;
t105 = t61+t67;
t113 = in20+t33+t34+t66;
t123 = t43+t63+t64;
t124 = t46+t63+t65;
t128 = t31.*t115;
t136 = t47+t55+t56+t68+t72;
t75 = -t73;
t84 = in1.*t27.*t57;
t85 = in2.*t27.*t57;
t87 = in15.*t27.*t57;
t88 = in16.*t27.*t57;
t97 = t57.*t58;
t98 = -t95;
t99 = -t96;
t101 = (in1.*t23.*t28.*t57)./2.0;
t102 = (in2.*t23.*t28.*t57)./2.0;
t104 = t4+t5+t51+t71;
t108 = in1.*t105;
t109 = in2.*t105;
t121 = t79+t80-1.0;
t126 = in2.*t27.*(t6+t7-t70+t17.*t35);
t127 = t31.*t113;
t131 = t31.*t123;
t132 = t31.*t124;
t138 = t31.*t136;
t103 = -t102;
t114 = -t109;
t116 = in1.*t27.*t104;
t117 = in2.*t27.*t104;
t118 = t31.*t104;
t122 = t76+t85-1.0;
t129 = t84+t92;
t133 = t15+t75+t108;
out1 = in7.*in24.*(-in16+t97+t31.*(t6+t7-t70+t17.*t35)).*-2.0-in10.*in21.*(-in16+t97+t31.*(t6+t7-t70+t17.*t35)).*2.0+in21.*in24.*(in2-t31.*t57).*2.0-in7.*in10.*(t31.*t133+t23.*t27.*(t6+t7-t70+t17.*t35)-(t24.*t28.*t57)./4.0+(t26.*t27.*t57)./2.0);
if nargout > 1
    t134 = t14+t74+t114;
    t135 = t17+t94+t118;
    out2 = in21.*in24.*(in1-t31.*t54).*-2.0+in7.*in10.*(t54.*t61+t31.*t134-(t24.*t28.*t54)./4.0+t23.*t27.*t104)+in7.*in24.*t135.*2.0+in10.*in21.*t135.*2.0;
end
if nargout > 2
    t139 = t82+t91+t98+t116+t128;
    et1 = in4.*in21.*in24.*t121.*-2.0-in7.*in18.*in24.*t121.*2.0-in10.*in18.*in21.*t121.*2.0-in4.*in7.*in24.*t139.*2.0-in4.*in10.*in21.*t139.*2.0-in7.*in10.*in18.*t139.*2.0+in3.*in21.*in24.*t129.*2.0+in7.*in17.*in24.*t129.*2.0+in10.*in17.*in21.*t129.*2.0+in3.*in7.*in10.*(t61.*t77+t31.*(t105+t18.*t27+t8.*t24.*t29.*(3.0./4.0)-(t8.*t26.*t28)./2.0-in1.*in15.*t23.*t28.*2.0)+in15.*t27.*(t6+t7-t70+t17.*t35).*2.0+in1.*t27.*t133-(t24.*t28.*t77)./4.0-t23.*t27.*t123-in1.*t23.*t28.*(t6+t7-t70+t17.*t35)+in1.*t24.*t29.*t57.*(3.0./4.0)-(in1.*t26.*t28.*t57)./2.0+t17.*t23.*t28.*t57)+in3.*in7.*in24.*(t87-t101+t106-t131+in1.*t27.*(t6+t7-t70+t17.*t35)).*2.0;
    et2 = in3.*in10.*in21.*(t87-t101+t106-t131+in1.*t27.*(t6+t7-t70+t17.*t35)).*2.0+in7.*in10.*in17.*(t87-t101+t106-t131+in1.*t27.*(t6+t7-t70+t17.*t35)).*2.0-in4.*in7.*in10.*(t138+t52.*t61+in15.*t27.*t104.*2.0+in1.*t27.*t134-(t24.*t28.*t52)./4.0+t23.*t27.*t115+in1.*t24.*t29.*t54.*(3.0./4.0)-(in1.*t26.*t28.*t54)./2.0-in1.*t23.*t28.*t104+t17.*t23.*t28.*t54);
    out3 = et1+et2;
end
if nargout > 3
    t140 = t88+t90+t103+t126+t127;
    t141 = t83+t99+t111+t117+t132;
    et3 = in3.*in21.*in24.*t122.*2.0+in7.*in17.*in24.*t122.*2.0+in10.*in17.*in21.*t122.*2.0+in3.*in7.*in24.*t140.*2.0+in3.*in10.*in21.*t140.*2.0+in7.*in10.*in17.*t140.*2.0-in4.*in7.*in24.*t141.*2.0-in4.*in10.*in21.*t141.*2.0-in7.*in10.*in18.*t141.*2.0+in4.*in7.*in10.*(t61.*t78+t31.*(t105+t19.*t27+t9.*t24.*t29.*(3.0./4.0)-(t9.*t26.*t28)./2.0-in2.*in16.*t23.*t28.*2.0)-in16.*t27.*t104.*2.0-in2.*t27.*t134-(t24.*t28.*t78)./4.0-t23.*t27.*t124-in2.*t24.*t29.*t54.*(3.0./4.0)+(in2.*t26.*t28.*t54)./2.0+in16.*t23.*t28.*t54+in2.*t23.*t28.*t104)-in4.*in21.*in24.*(t81-t93).*2.0-in7.*in18.*in24.*(t81-t93).*2.0-in10.*in18.*in21.*(t81-t93).*2.0;
    et4 = -in3.*in7.*in10.*(t138+t41.*t62-in16.*t27.*(t6+t7-t70+t17.*t35).*2.0-in2.*t27.*t133-(t26.*t27.*t41)./2.0-t23.*t27.*t113+in2.*t23.*t28.*(t6+t7-t70+t17.*t35)-in2.*t24.*t29.*t57.*(3.0./4.0)+(in2.*t26.*t28.*t57)./2.0+in16.*t23.*t28.*t57);
    out4 = et3+et4;
end
end

