function varargout=F_seg1(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:13);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',9);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_seg1_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_seg1_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26)
%F_seg1_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    12-Aug-2025 15:59:23

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.^2;
t5 = in2.^2;
t6 = -in5;
t7 = t4+t5;
t8 = sqrt(t7);
t9 = 1.0./t8;
t10 = -t8;
t11 = t8-1.0;
t12 = in1.*in2.*t9;
t13 = in5+t10;
t14 = in1.*t13;
t15 = in2.*t13;
t16 = -t14;
t17 = t2+t15;
t18 = t3+t16;
out1 = in9.*(in2-t11.*t18);
if nargout > 1
    out2 = -in9.*(in1-t11.*t17);
end
if nargout > 2
    out3 = in3.*in9.*(t11.*(t6+t8+t4.*t9)+in1.*t9.*t18)-in4.*in9.*(t11.*(in6-t12)+in1.*t9.*t17-1.0);
end
if nargout > 3
    out4 = in3.*in9.*(t11.*(in6+t12)+in2.*t9.*t18-1.0)+in4.*in9.*(t11.*(t6+t8+t5.*t9)-in2.*t9.*t17);
end
end


function [out1,out2,out3,out4] = F_seg1_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26)
%F_seg1_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    12-Aug-2025 15:59:24

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in19;
t5 = in6.*in14;
t6 = in2.*in19;
t7 = in6.*in15;
t8 = in1.^2;
t9 = in2.^2;
t10 = in1.*in14.*2.0;
t11 = in2.*in15.*2.0;
t12 = -in5;
t15 = t8+t9;
t16 = t10+t11;
t17 = sqrt(t15);
t18 = 1.0./t17;
t20 = -t17;
t21 = t17-1.0;
t19 = t18.^3;
t22 = in1.*in2.*t18;
t23 = in1.*in15.*t18;
t24 = in2.*in14.*t18;
t25 = in5+t20;
t26 = t8.*t18;
t27 = t9.*t18;
t38 = (t16.*t18)./2.0;
t28 = in6+t22;
t29 = -t22;
t30 = in1.*t25;
t31 = in2.*t25;
t32 = in14.*t25;
t33 = in15.*t25;
t39 = -t38;
t40 = (in1.*in2.*t16.*t19)./2.0;
t45 = t12+t17+t26;
t46 = t12+t17+t27;
t34 = in6+t29;
t35 = -t30;
t36 = t2+t31;
t41 = in18+t39;
t44 = t21.*t28;
t53 = t21.*t45;
t54 = t21.*t46;
t37 = t3+t35;
t42 = in1.*t41;
out1 = in22.*(in2-t21.*t37)-in9.*(-in15+t37.*t38+t21.*(t6+t7-t32-t42));
if nargout > 1
    t43 = in2.*t41;
    t47 = t21.*t34;
    t48 = in1.*t18.*t36;
    t49 = in2.*t18.*t36;
    t50 = in1.*t18.*t37;
    t51 = in2.*t18.*t37;
    t55 = t4+t5+t33+t43;
    out2 = in9.*(-in14+t36.*t38+t21.*t55)-in22.*(in1-t21.*t36);
end
if nargout > 2
    t57 = t47+t48-1.0;
    t58 = t44+t51-1.0;
    t59 = t50+t53;
    out3 = -in4.*in9.*(t34.*t38+t21.*(in19-t23-t24+t40)+in14.*t18.*t36+in1.*t18.*t55-(in1.*t16.*t19.*t36)./2.0)-in4.*in22.*t57-in9.*in17.*t57+in3.*in22.*t59+in9.*in16.*t59+in3.*in9.*(-t21.*(t41-in1.*in14.*t18.*2.0+(t8.*t16.*t19)./2.0)+t38.*t45+in1.*t18.*(t6+t7-t32-t42)+in14.*t18.*t37-(in1.*t16.*t19.*t37)./2.0);
end
if nargout > 3
    out4 = in3.*in9.*(t28.*t38+t21.*(in19+t23+t24-t40)+in2.*t18.*(t6+t7-t32-t42)+in15.*t18.*t37-(in2.*t16.*t19.*t37)./2.0)+in3.*in22.*t58+in9.*in16.*t58-in4.*in22.*(t49-t54)-in9.*in17.*(t49-t54)-in4.*in9.*(t21.*(t41-in2.*in15.*t18.*2.0+(t9.*t16.*t19)./2.0)+in15.*t18.*t36+in2.*t18.*t55-(t16.*t18.*t46)./2.0-(in2.*t16.*t19.*t36)./2.0);
end
end


function [out1,out2,out3,out4] = F_seg1_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26)
%F_seg1_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    12-Aug-2025 15:59:24

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in19;
t5 = in6.*in14;
t6 = in2.*in19;
t7 = in6.*in15;
t8 = in1.^2;
t9 = in2.^2;
t10 = in14.^2;
t11 = in15.^2;
t12 = in1.*in14.*2.0;
t13 = in2.*in15.*2.0;
t14 = in14.*in19.*2.0;
t15 = in15.*in19.*2.0;
t16 = -in5;
t17 = t10.*2.0;
t18 = t11.*2.0;
t21 = t8+t9;
t22 = t12+t13;
t23 = t22.^2;
t24 = sqrt(t21);
t25 = t17+t18;
t26 = 1.0./t24;
t29 = -t24;
t30 = t24-1.0;
t27 = t26.^3;
t28 = t26.^5;
t31 = in1.*in2.*t26;
t32 = in1.*in15.*t26;
t33 = in2.*in14.*t26;
t34 = in5+t29;
t35 = t8.*t26;
t36 = t9.*t26;
t39 = in14.*in15.*t26.*2.0;
t42 = in1.*in14.*t26.*-2.0;
t45 = in2.*in15.*t26.*-2.0;
t57 = (t22.*t26)./2.0;
t60 = (t25.*t26)./2.0;
t40 = in6+t31;
t41 = -t31;
t43 = -t32;
t44 = -t33;
t46 = -t39;
t47 = in1.*t34;
t48 = in2.*t34;
t49 = in14.*t34;
t50 = in15.*t34;
t54 = in1.*in15.*t22.*t27;
t55 = in2.*in14.*t22.*t27;
t58 = -t57;
t59 = (in1.*in2.*t22.*t27)./2.0;
t61 = (t23.*t27)./4.0;
t63 = (t8.*t22.*t27)./2.0;
t64 = (t9.*t22.*t27)./2.0;
t67 = (in1.*in2.*t25.*t27)./2.0;
t68 = in1.*in2.*t23.*t28.*(3.0./4.0);
t75 = t16+t24+t35;
t76 = t16+t24+t36;
t51 = in6+t41;
t52 = -t47;
t53 = t2+t48;
t62 = in18+t58;
t65 = -t59;
t66 = -t61;
t71 = -t68;
t82 = t40.*t57;
t93 = t57.*t75;
t98 = t22.*t26.*t76.*(-1.0./2.0);
t102 = in19+t43+t44+t59;
t56 = t3+t52;
t69 = in1.*t62;
t70 = in2.*t62;
t72 = in14.*t62.*2.0;
t73 = in15.*t62.*2.0;
t77 = in14.*t26.*t53;
t78 = in15.*t26.*t53;
t83 = t51.*t57;
t84 = (in1.*t22.*t27.*t53)./2.0;
t85 = (in2.*t22.*t27.*t53)./2.0;
t92 = t60+t66;
t100 = in19+t32+t33+t65;
t107 = t42+t62+t63;
t108 = t45+t62+t64;
t111 = t30.*t102;
t116 = t46+t54+t55+t67+t71;
t74 = -t72;
t79 = in14.*t26.*t56;
t80 = in15.*t26.*t56;
t86 = -t84;
t87 = -t85;
t88 = (in1.*t22.*t27.*t56)./2.0;
t89 = (in2.*t22.*t27.*t56)./2.0;
t91 = t4+t5+t50+t70;
t95 = in1.*t92;
t96 = in2.*t92;
t109 = in2.*t26.*(t6+t7-t49-t69);
t110 = t30.*t100;
t112 = t30.*t107;
t113 = t30.*t108;
t117 = t30.*t116;
t90 = -t89;
t101 = -t96;
t103 = in1.*t26.*t91;
t104 = in2.*t26.*t91;
t114 = t15+t74+t95;
out1 = -in9.*(t30.*t114+t22.*t26.*(t6+t7-t49-t69)-(t23.*t27.*t56)./4.0+(t25.*t26.*t56)./2.0)-in22.*(-in15+t56.*t57+t30.*(t6+t7-t49-t69)).*2.0;
if nargout > 1
    t115 = t14+t73+t101;
    out2 = in9.*(t53.*t60+t30.*t115-(t23.*t27.*t53)./4.0+t22.*t26.*t91)+in22.*(-in14+t53.*t57+t30.*t91).*2.0;
end
if nargout > 2
    t118 = t77+t83+t86+t103+t111;
    et1 = in3.*in9.*(t30.*(t92+t17.*t26+t8.*t23.*t28.*(3.0./4.0)-(t8.*t25.*t27)./2.0-in1.*in14.*t22.*t27.*2.0)+in14.*t26.*(t6+t7-t49-t69).*2.0+in1.*t26.*t114-(t23.*t27.*t75)./4.0+(t25.*t26.*t75)./2.0-t22.*t26.*t107+in1.*t23.*t28.*t56.*(3.0./4.0)-(in1.*t25.*t27.*t56)./2.0-in14.*t22.*t27.*t56-in1.*t22.*t27.*(t6+t7-t49-t69))+in3.*in22.*(t79-t88+t93-t112+in1.*t26.*(t6+t7-t49-t69)).*2.0+in9.*in16.*(t79-t88+t93-t112+in1.*t26.*(t6+t7-t49-t69)).*2.0-in17.*in22.*(t30.*t51+in1.*t26.*t53-1.0).*2.0+in16.*in22.*(t30.*t75+in1.*t26.*t56).*2.0;
    et2 = in4.*in22.*t118.*-2.0-in9.*in17.*t118.*2.0-in4.*in9.*(t117+t51.*t60+in14.*t26.*t91.*2.0+in1.*t26.*t115-(t23.*t27.*t51)./4.0+t22.*t26.*t102+in1.*t23.*t28.*t53.*(3.0./4.0)-(in1.*t25.*t27.*t53)./2.0-in14.*t22.*t27.*t53-in1.*t22.*t27.*t91);
    out3 = et1+et2;
end
if nargout > 3
    t119 = t80+t82+t90+t109+t110;
    t120 = t78+t87+t98+t104+t113;
    et3 = in16.*in22.*(t30.*t40+in2.*t26.*t56-1.0).*2.0+in17.*in22.*(t30.*t76-in2.*t26.*t53).*2.0+in3.*in22.*t119.*2.0+in9.*in16.*t119.*2.0-in4.*in22.*t120.*2.0-in9.*in17.*t120.*2.0-in3.*in9.*(t117+t40.*t61-in15.*t26.*(t6+t7-t49-t69).*2.0-in2.*t26.*t114-(t25.*t26.*t40)./2.0-t22.*t26.*t100-in2.*t23.*t28.*t56.*(3.0./4.0)+(in2.*t25.*t27.*t56)./2.0+in15.*t22.*t27.*t56+in2.*t22.*t27.*(t6+t7-t49-t69));
    et4 = in4.*in9.*(t60.*t76+t30.*(t92+t18.*t26+t9.*t23.*t28.*(3.0./4.0)-(t9.*t25.*t27)./2.0-in2.*in15.*t22.*t27.*2.0)-in15.*t26.*t91.*2.0-in2.*t26.*t115-(t23.*t27.*t76)./4.0-t22.*t26.*t108-in2.*t23.*t28.*t53.*(3.0./4.0)+(in2.*t25.*t27.*t53)./2.0+in15.*t22.*t27.*t53+in2.*t22.*t27.*t91);
    out4 = et3+et4;
end
end

