function varargout=F_seg3(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('x',1:2,'p',3:11);
   return
  case 'argsize'
   varargout{1}=struct('x',2,'p',9);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('F_seg3_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = F_seg3_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22)
%F_seg3_rhs_0
%    [OUT1,OUT2] = F_seg3_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:01

t2 = in1.^2;
t3 = in2.^2;
t4 = in6-1.0;
t5 = t2+t3;
t6 = sqrt(t5);
t7 = -t6;
t8 = t6-1.0;
t9 = in3+t7;
out1 = -t4.*(in2-t8.*(in2.*in4-in1.*t9));
if nargout > 1
    out2 = t4.*(in1-t8.*(in1.*in4+in2.*t9));
end
end


function [out1,out2] = F_seg3_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22)
%F_seg3_rhs_1
%    [OUT1,OUT2] = F_seg3_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:01

t2 = in1.*in4;
t3 = in2.*in4;
t4 = in1.^2;
t5 = in2.^2;
t6 = in1.*in12.*2.0;
t7 = in2.*in13.*2.0;
t8 = in6-1.0;
t9 = t4+t5;
t10 = t6+t7;
t11 = sqrt(t9);
t12 = 1.0./t11;
t13 = -t11;
t14 = t11-1.0;
t15 = in3+t13;
t21 = (t10.*t12)./2.0;
t16 = in1.*t15;
t17 = in2.*t15;
t22 = -t21;
t18 = -t16;
t19 = t2+t17;
t23 = in14+t22;
t20 = t3+t18;
out1 = t8.*(-in13+t14.*(in2.*in15+in4.*in13-in1.*t23-in12.*t15)+t20.*t21)-in17.*(in2-t14.*t20);
if nargout > 1
    out2 = -t8.*(-in12+t14.*(in1.*in15+in4.*in12+in2.*t23+in13.*t15)+t19.*t21)+in17.*(in1-t14.*t19);
end
end


function [out1,out2] = F_seg3_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22)
%F_seg3_rhs_2
%    [OUT1,OUT2] = F_seg3_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:01

t2 = in1.*in4;
t3 = in2.*in4;
t4 = in1.*in15;
t5 = in4.*in12;
t6 = in2.*in15;
t7 = in4.*in13;
t8 = in1.^2;
t9 = in2.^2;
t10 = in12.^2;
t11 = in13.^2;
t12 = in1.*in12.*2.0;
t13 = in2.*in13.*2.0;
t14 = in6-1.0;
t15 = t10.*2.0;
t16 = t11.*2.0;
t19 = t8+t9;
t20 = t12+t13;
t21 = t20.^2;
t22 = sqrt(t19);
t23 = t15+t16;
t24 = 1.0./t22;
t26 = -t22;
t27 = t22-1.0;
t25 = t24.^3;
t28 = in3+t26;
t36 = (t20.*t24)./2.0;
t38 = (t23.*t24)./2.0;
t29 = in1.*t28;
t30 = in2.*t28;
t31 = in12.*t28;
t32 = in13.*t28;
t37 = -t36;
t39 = (t21.*t25)./4.0;
t33 = -t29;
t34 = t2+t30;
t40 = in14+t37;
t41 = -t39;
t35 = t3+t33;
t42 = in1.*t40;
t43 = in2.*t40;
t45 = t38+t41;
out1 = t14.*(t27.*(in13.*in15.*2.0+in1.*t45-in12.*t40.*2.0)+t20.*t24.*(t6+t7-t31-t42)-(t21.*t25.*t35)./4.0+(t23.*t24.*t35)./2.0)+in17.*(-in13+t35.*t36+t27.*(t6+t7-t31-t42)).*2.0;
if nargout > 1
    t44 = t4+t5+t32+t43;
    out2 = in17.*(-in12+t34.*t36+t27.*t44).*-2.0-t14.*(t34.*t38+t27.*(in12.*in15.*2.0-in2.*t45+in13.*t40.*2.0)-(t21.*t25.*t34)./4.0+t20.*t24.*t44);
end
end

