function varargout=F_seg2(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:13);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',9);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_seg2_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_seg2_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26)
%F_seg2_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 15:42:17

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.^2;
t5 = in2.^2;
t6 = -in5;
t7 = in9-1.0;
t8 = t4+t5;
t9 = sqrt(t8);
t10 = 1.0./t9;
t11 = -t9;
t12 = t9-1.0;
t13 = in1.*in2.*t10;
t14 = in5+t11;
t15 = in1.*t14;
t16 = in2.*t14;
t17 = -t15;
t18 = t2+t16;
t19 = t3+t17;
out1 = -t7.*(in2-t12.*t19);
if nargout > 1
    out2 = t7.*(in1-t12.*t18);
end
if nargout > 2
    out3 = -in3.*t7.*(t12.*(t6+t9+t4.*t10)+in1.*t10.*t19)+in4.*t7.*(t12.*(in6-t13)+in1.*t10.*t18-1.0);
end
if nargout > 3
    out4 = -in3.*t7.*(t12.*(in6+t13)+in2.*t10.*t19-1.0)-in4.*t7.*(t12.*(t6+t9+t5.*t10)-in2.*t10.*t18);
end
end


function [out1,out2,out3,out4] = F_seg2_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26)
%F_seg2_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 15:42:17

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in19;
t5 = in6.*in14;
t6 = in2.*in19;
t7 = in6.*in15;
t8 = in1.^2;
t9 = in2.^2;
t10 = in1.*in14.*2.0;
t11 = in2.*in15.*2.0;
t12 = -in5;
t13 = in9-1.0;
t16 = t8+t9;
t17 = t10+t11;
t18 = sqrt(t16);
t19 = 1.0./t18;
t21 = -t18;
t22 = t18-1.0;
t20 = t19.^3;
t23 = in1.*in2.*t19;
t24 = in1.*in15.*t19;
t25 = in2.*in14.*t19;
t26 = in5+t21;
t27 = t8.*t19;
t28 = t9.*t19;
t39 = (t17.*t19)./2.0;
t29 = in6+t23;
t30 = -t23;
t31 = in1.*t26;
t32 = in2.*t26;
t33 = in14.*t26;
t34 = in15.*t26;
t40 = -t39;
t41 = (in1.*in2.*t17.*t20)./2.0;
t46 = t12+t18+t27;
t47 = t12+t18+t28;
t35 = in6+t30;
t36 = -t31;
t37 = t2+t32;
t42 = in18+t40;
t45 = t22.*t29;
t54 = t22.*t46;
t55 = t22.*t47;
t38 = t3+t36;
t43 = in1.*t42;
out1 = t13.*(-in15+t38.*t39+t22.*(t6+t7-t33-t43))-in22.*(in2-t22.*t38);
if nargout > 1
    t44 = in2.*t42;
    t48 = t22.*t35;
    t49 = in1.*t19.*t37;
    t50 = in2.*t19.*t37;
    t51 = in1.*t19.*t38;
    t52 = in2.*t19.*t38;
    t56 = t4+t5+t34+t44;
    out2 = -t13.*(-in14+t37.*t39+t22.*t56)+in22.*(in1-t22.*t37);
end
if nargout > 2
    t58 = t48+t49-1.0;
    t59 = t45+t52-1.0;
    t60 = t51+t54;
    out3 = in4.*t13.*(t35.*t39+t22.*(in19-t24-t25+t41)+in14.*t19.*t37+in1.*t19.*t56-(in1.*t17.*t20.*t37)./2.0)+in4.*in22.*t58-in3.*in22.*t60+in17.*t13.*t58-in16.*t13.*t60-in3.*t13.*(-t22.*(t42-in1.*in14.*t19.*2.0+(t8.*t17.*t20)./2.0)+t39.*t46+in1.*t19.*(t6+t7-t33-t43)+in14.*t19.*t38-(in1.*t17.*t20.*t38)./2.0);
end
if nargout > 3
    out4 = -in3.*t13.*(t29.*t39+t22.*(in19+t24+t25-t41)+in2.*t19.*(t6+t7-t33-t43)+in15.*t19.*t38-(in2.*t17.*t20.*t38)./2.0)-in3.*in22.*t59-in16.*t13.*t59+in4.*in22.*(t50-t55)+in17.*t13.*(t50-t55)+in4.*t13.*(t22.*(t42-in2.*in15.*t19.*2.0+(t9.*t17.*t20)./2.0)+in15.*t19.*t37+in2.*t19.*t56-(t17.*t19.*t47)./2.0-(in2.*t17.*t20.*t37)./2.0);
end
end


function [out1,out2,out3,out4] = F_seg2_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26)
%F_seg2_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 15:42:17

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in19;
t5 = in6.*in14;
t6 = in2.*in19;
t7 = in6.*in15;
t8 = in1.^2;
t9 = in2.^2;
t10 = in14.^2;
t11 = in15.^2;
t12 = in1.*in14.*2.0;
t13 = in2.*in15.*2.0;
t14 = in14.*in19.*2.0;
t15 = in15.*in19.*2.0;
t16 = -in5;
t17 = in9-1.0;
t18 = t10.*2.0;
t19 = t11.*2.0;
t22 = t8+t9;
t23 = t12+t13;
t24 = t23.^2;
t25 = sqrt(t22);
t26 = t18+t19;
t27 = 1.0./t25;
t30 = -t25;
t31 = t25-1.0;
t28 = t27.^3;
t29 = t27.^5;
t32 = in1.*in2.*t27;
t33 = in1.*in15.*t27;
t34 = in2.*in14.*t27;
t35 = in5+t30;
t36 = t8.*t27;
t37 = t9.*t27;
t40 = in14.*in15.*t27.*2.0;
t43 = in1.*in14.*t27.*-2.0;
t46 = in2.*in15.*t27.*-2.0;
t58 = (t23.*t27)./2.0;
t61 = (t26.*t27)./2.0;
t41 = in6+t32;
t42 = -t32;
t44 = -t33;
t45 = -t34;
t47 = -t40;
t48 = in1.*t35;
t49 = in2.*t35;
t50 = in14.*t35;
t51 = in15.*t35;
t55 = in1.*in15.*t23.*t28;
t56 = in2.*in14.*t23.*t28;
t59 = -t58;
t60 = (in1.*in2.*t23.*t28)./2.0;
t62 = (t24.*t28)./4.0;
t64 = (t8.*t23.*t28)./2.0;
t65 = (t9.*t23.*t28)./2.0;
t68 = (in1.*in2.*t26.*t28)./2.0;
t69 = in1.*in2.*t24.*t29.*(3.0./4.0);
t76 = t16+t25+t36;
t77 = t16+t25+t37;
t52 = in6+t42;
t53 = -t48;
t54 = t2+t49;
t63 = in18+t59;
t66 = -t60;
t67 = -t62;
t72 = -t69;
t83 = t41.*t58;
t94 = t58.*t76;
t99 = t23.*t27.*t77.*(-1.0./2.0);
t103 = in19+t44+t45+t60;
t57 = t3+t53;
t70 = in1.*t63;
t71 = in2.*t63;
t73 = in14.*t63.*2.0;
t74 = in15.*t63.*2.0;
t78 = in14.*t27.*t54;
t79 = in15.*t27.*t54;
t84 = t52.*t58;
t85 = (in1.*t23.*t28.*t54)./2.0;
t86 = (in2.*t23.*t28.*t54)./2.0;
t93 = t61+t67;
t101 = in19+t33+t34+t66;
t108 = t43+t63+t64;
t109 = t46+t63+t65;
t112 = t31.*t103;
t117 = t47+t55+t56+t68+t72;
t75 = -t73;
t80 = in14.*t27.*t57;
t81 = in15.*t27.*t57;
t87 = -t85;
t88 = -t86;
t89 = (in1.*t23.*t28.*t57)./2.0;
t90 = (in2.*t23.*t28.*t57)./2.0;
t92 = t4+t5+t51+t71;
t96 = in1.*t93;
t97 = in2.*t93;
t110 = in2.*t27.*(t6+t7-t50-t70);
t111 = t31.*t101;
t113 = t31.*t108;
t114 = t31.*t109;
t118 = t31.*t117;
t91 = -t90;
t102 = -t97;
t104 = in1.*t27.*t92;
t105 = in2.*t27.*t92;
t115 = t15+t75+t96;
out1 = t17.*(t31.*t115+t23.*t27.*(t6+t7-t50-t70)-(t24.*t28.*t57)./4.0+(t26.*t27.*t57)./2.0)+in22.*(-in15+t57.*t58+t31.*(t6+t7-t50-t70)).*2.0;
if nargout > 1
    t116 = t14+t74+t102;
    out2 = -t17.*(t54.*t61+t31.*t116-(t24.*t28.*t54)./4.0+t23.*t27.*t92)-in22.*(-in14+t54.*t58+t31.*t92).*2.0;
end
if nargout > 2
    t119 = t78+t84+t87+t104+t112;
    et1 = -in3.*t17.*(t31.*(t93+t18.*t27+t8.*t24.*t29.*(3.0./4.0)-(t8.*t26.*t28)./2.0-in1.*in14.*t23.*t28.*2.0)+in14.*t27.*(t6+t7-t50-t70).*2.0+in1.*t27.*t115-(t24.*t28.*t76)./4.0+(t26.*t27.*t76)./2.0-t23.*t27.*t108+in1.*t24.*t29.*t57.*(3.0./4.0)-(in1.*t26.*t28.*t57)./2.0-in14.*t23.*t28.*t57-in1.*t23.*t28.*(t6+t7-t50-t70))-in3.*in22.*(t80-t89+t94-t113+in1.*t27.*(t6+t7-t50-t70)).*2.0-in16.*t17.*(t80-t89+t94-t113+in1.*t27.*(t6+t7-t50-t70)).*2.0+in17.*in22.*(t31.*t52+in1.*t27.*t54-1.0).*2.0;
    et2 = in16.*in22.*(t31.*t76+in1.*t27.*t57).*-2.0+in4.*in22.*t119.*2.0+in17.*t17.*t119.*2.0+in4.*t17.*(t118+t52.*t61+in14.*t27.*t92.*2.0+in1.*t27.*t116-(t24.*t28.*t52)./4.0+t23.*t27.*t103+in1.*t24.*t29.*t54.*(3.0./4.0)-(in1.*t26.*t28.*t54)./2.0-in14.*t23.*t28.*t54-in1.*t23.*t28.*t92);
    out3 = et1+et2;
end
if nargout > 3
    t120 = t81+t83+t91+t110+t111;
    t121 = t79+t88+t99+t105+t114;
    et3 = in16.*in22.*(t31.*t41+in2.*t27.*t57-1.0).*-2.0-in17.*in22.*(t31.*t77-in2.*t27.*t54).*2.0-in3.*in22.*t120.*2.0+in4.*in22.*t121.*2.0-in16.*t17.*t120.*2.0+in17.*t17.*t121.*2.0+in3.*t17.*(t118+t41.*t62-in15.*t27.*(t6+t7-t50-t70).*2.0-in2.*t27.*t115-(t26.*t27.*t41)./2.0-t23.*t27.*t101-in2.*t24.*t29.*t57.*(3.0./4.0)+(in2.*t26.*t28.*t57)./2.0+in15.*t23.*t28.*t57+in2.*t23.*t28.*(t6+t7-t50-t70));
    et4 = -in4.*t17.*(t61.*t77+t31.*(t93+t19.*t27+t9.*t24.*t29.*(3.0./4.0)-(t9.*t26.*t28)./2.0-in2.*in15.*t23.*t28.*2.0)-in15.*t27.*t92.*2.0-in2.*t27.*t116-(t24.*t28.*t77)./4.0-t23.*t27.*t109-in2.*t24.*t29.*t54.*(3.0./4.0)+(in2.*t26.*t28.*t54)./2.0+in15.*t23.*t28.*t54+in2.*t23.*t28.*t92);
    out4 = et3+et4;
end
end

