function varargout=F_seg4(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('x',1:2,'p',3:11);
   return
  case 'argsize'
   varargout{1}=struct('x',2,'p',9);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('F_seg4_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = F_seg4_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22)
%F_seg4_rhs_0
%    [OUT1,OUT2] = F_seg4_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:01

t2 = in1.^2;
t3 = in2.^2;
t4 = t2+t3;
t5 = sqrt(t4);
t6 = -t5;
t7 = t5-1.0;
t8 = in3+t6;
out1 = in5.*(in2-t7.*(in2.*in4-in1.*t8));
if nargout > 1
    out2 = -in5.*(in1-t7.*(in1.*in4+in2.*t8));
end
end


function [out1,out2] = F_seg4_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22)
%F_seg4_rhs_1
%    [OUT1,OUT2] = F_seg4_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:02

t2 = in1.*in4;
t3 = in2.*in4;
t4 = in1.^2;
t5 = in2.^2;
t6 = in1.*in12.*2.0;
t7 = in2.*in13.*2.0;
t8 = t4+t5;
t9 = t6+t7;
t10 = sqrt(t8);
t11 = 1.0./t10;
t12 = -t10;
t13 = t10-1.0;
t14 = in3+t12;
t20 = (t9.*t11)./2.0;
t15 = in1.*t14;
t16 = in2.*t14;
t21 = -t20;
t17 = -t15;
t18 = t2+t16;
t22 = in14+t21;
t19 = t3+t17;
out1 = -in5.*(-in13+t13.*(in2.*in15+in4.*in13-in1.*t22-in12.*t14)+t19.*t20)+in16.*(in2-t13.*t19);
if nargout > 1
    out2 = in5.*(-in12+t13.*(in1.*in15+in4.*in12+in2.*t22+in13.*t14)+t18.*t20)-in16.*(in1-t13.*t18);
end
end


function [out1,out2] = F_seg4_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22)
%F_seg4_rhs_2
%    [OUT1,OUT2] = F_seg4_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 13:35:02

t2 = in1.*in4;
t3 = in2.*in4;
t4 = in1.*in15;
t5 = in4.*in12;
t6 = in2.*in15;
t7 = in4.*in13;
t8 = in1.^2;
t9 = in2.^2;
t10 = in12.^2;
t11 = in13.^2;
t12 = in1.*in12.*2.0;
t13 = in2.*in13.*2.0;
t14 = t10.*2.0;
t15 = t11.*2.0;
t18 = t8+t9;
t19 = t12+t13;
t20 = t19.^2;
t21 = sqrt(t18);
t22 = t14+t15;
t23 = 1.0./t21;
t25 = -t21;
t26 = t21-1.0;
t24 = t23.^3;
t27 = in3+t25;
t35 = (t19.*t23)./2.0;
t37 = (t22.*t23)./2.0;
t28 = in1.*t27;
t29 = in2.*t27;
t30 = in12.*t27;
t31 = in13.*t27;
t36 = -t35;
t38 = (t20.*t24)./4.0;
t32 = -t28;
t33 = t2+t29;
t39 = in14+t36;
t40 = -t38;
t34 = t3+t32;
t41 = in1.*t39;
t42 = in2.*t39;
t44 = t37+t40;
out1 = -in5.*(t26.*(in13.*in15.*2.0+in1.*t44-in12.*t39.*2.0)+t19.*t23.*(t6+t7-t30-t41)-(t20.*t24.*t34)./4.0+(t22.*t23.*t34)./2.0)-in16.*(-in13+t34.*t35+t26.*(t6+t7-t30-t41)).*2.0;
if nargout > 1
    t43 = t4+t5+t31+t42;
    out2 = in16.*(-in12+t33.*t35+t26.*t43).*2.0+in5.*(t33.*t37+t26.*(in12.*in15.*2.0-in2.*t44+in13.*t39.*2.0)-(t20.*t24.*t33)./4.0+t19.*t23.*t43);
end
end

