function varargout=F_VAR(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:8);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',4);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_VAR_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_VAR_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16)
%F_VAR_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_VAR_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    12-Aug-2025 15:59:22

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.^2;
t5 = in2.^2;
t6 = -in5;
t7 = t4+t5;
t8 = sqrt(t7);
t9 = 1.0./t8;
t10 = -t8;
t11 = t8-1.0;
t12 = in1.*in2.*t9;
t13 = in5+t10;
t14 = in1.*t13;
t15 = in2.*t13;
t16 = -t14;
t17 = t2+t15;
t18 = t3+t16;
out1 = in2-t11.*t18;
if nargout > 1
    out2 = -in1+t11.*t17;
end
if nargout > 2
    out3 = in3.*(t11.*(t6+t8+t4.*t9)+in1.*t9.*t18)-in4.*(t11.*(in6-t12)+in1.*t9.*t17-1.0);
end
if nargout > 3
    out4 = in4.*(t11.*(t6+t8+t5.*t9)-in2.*t9.*t17)+in3.*(t11.*(in6+t12)+in2.*t9.*t18-1.0);
end
end


function [out1,out2,out3,out4] = F_VAR_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16)
%F_VAR_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_VAR_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    12-Aug-2025 15:59:23

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in14;
t5 = in6.*in9;
t6 = in2.*in14;
t7 = in6.*in10;
t8 = in1.^2;
t9 = in2.^2;
t10 = in1.*in9.*2.0;
t11 = in2.*in10.*2.0;
t12 = -in5;
t15 = t8+t9;
t16 = t10+t11;
t17 = sqrt(t15);
t18 = 1.0./t17;
t20 = -t17;
t21 = t17-1.0;
t19 = t18.^3;
t22 = in1.*in2.*t18;
t23 = in1.*in10.*t18;
t24 = in2.*in9.*t18;
t25 = in5+t20;
t26 = t8.*t18;
t27 = t9.*t18;
t38 = (t16.*t18)./2.0;
t28 = in6+t22;
t29 = -t22;
t30 = in1.*t25;
t31 = in2.*t25;
t32 = in9.*t25;
t33 = in10.*t25;
t39 = -t38;
t40 = (in1.*in2.*t16.*t19)./2.0;
t44 = t12+t17+t26;
t45 = t12+t17+t27;
t34 = in6+t29;
t35 = -t30;
t36 = t2+t31;
t41 = in13+t39;
t37 = t3+t35;
t42 = in1.*t41;
out1 = in10-t21.*(t6+t7-t32-t42)-(t16.*t18.*t37)./2.0;
if nargout > 1
    t43 = in2.*t41;
    t46 = t4+t5+t33+t43;
    out2 = -in9+t21.*t46+t36.*t38;
end
if nargout > 2
    out3 = -in12.*(t21.*t34+in1.*t18.*t36-1.0)+in11.*(t21.*t44+in1.*t18.*t37)+in3.*(-t21.*(t41-in1.*in9.*t18.*2.0+(t8.*t16.*t19)./2.0)+t38.*t44+in1.*t18.*(t6+t7-t32-t42)+in9.*t18.*t37-(in1.*t16.*t19.*t37)./2.0)-in4.*(t34.*t38+t21.*(in14-t23-t24+t40)+in9.*t18.*t36+in1.*t18.*t46-(in1.*t16.*t19.*t36)./2.0);
end
if nargout > 3
    out4 = in11.*(t21.*t28+in2.*t18.*t37-1.0)+in12.*(t21.*t45-in2.*t18.*t36)-in4.*(t21.*(t41-in2.*in10.*t18.*2.0+(t9.*t16.*t19)./2.0)+in10.*t18.*t36+in2.*t18.*t46-(t16.*t18.*t45)./2.0-(in2.*t16.*t19.*t36)./2.0)+in3.*(t28.*t38+t21.*(in14+t23+t24-t40)+in2.*t18.*(t6+t7-t32-t42)+in10.*t18.*t37-(in2.*t16.*t19.*t37)./2.0);
end
end


function [out1,out2,out3,out4] = F_VAR_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16)
%F_VAR_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_VAR_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    12-Aug-2025 15:59:23

t2 = in1.*in6;
t3 = in2.*in6;
t4 = in1.*in14;
t5 = in6.*in9;
t6 = in2.*in14;
t7 = in6.*in10;
t8 = in1.^2;
t9 = in2.^2;
t10 = in9.^2;
t11 = in10.^2;
t12 = in1.*in9.*2.0;
t13 = in2.*in10.*2.0;
t14 = in9.*in14.*2.0;
t15 = in10.*in14.*2.0;
t16 = -in5;
t17 = t10.*2.0;
t18 = t11.*2.0;
t21 = t8+t9;
t22 = t12+t13;
t23 = t22.^2;
t24 = sqrt(t21);
t25 = t17+t18;
t26 = 1.0./t24;
t29 = -t24;
t30 = t24-1.0;
t27 = t26.^3;
t28 = t26.^5;
t31 = in1.*in2.*t26;
t32 = in1.*in10.*t26;
t33 = in2.*in9.*t26;
t34 = in5+t29;
t35 = t8.*t26;
t36 = t9.*t26;
t39 = in9.*in10.*t26.*2.0;
t42 = in1.*in9.*t26.*-2.0;
t45 = in2.*in10.*t26.*-2.0;
t57 = (t22.*t26)./2.0;
t60 = (t25.*t26)./2.0;
t40 = in6+t31;
t41 = -t31;
t43 = -t32;
t44 = -t33;
t46 = -t39;
t47 = in1.*t34;
t48 = in2.*t34;
t49 = in9.*t34;
t50 = in10.*t34;
t54 = in1.*in10.*t22.*t27;
t55 = in2.*in9.*t22.*t27;
t58 = -t57;
t59 = (in1.*in2.*t22.*t27)./2.0;
t61 = (t23.*t27)./4.0;
t63 = (t8.*t22.*t27)./2.0;
t64 = (t9.*t22.*t27)./2.0;
t67 = (in1.*in2.*t25.*t27)./2.0;
t68 = in1.*in2.*t23.*t28.*(3.0./4.0);
t75 = t16+t24+t35;
t76 = t16+t24+t36;
t51 = in6+t41;
t52 = -t47;
t53 = t2+t48;
t62 = in13+t58;
t65 = -t59;
t66 = -t61;
t71 = -t68;
t84 = in14+t43+t44+t59;
t56 = t3+t52;
t69 = in1.*t62;
t70 = in2.*t62;
t72 = in9.*t62.*2.0;
t73 = in10.*t62.*2.0;
t78 = t60+t66;
t82 = in14+t32+t33+t65;
t85 = t42+t62+t63;
t86 = t45+t62+t64;
t89 = t46+t54+t55+t67+t71;
t74 = -t72;
t77 = t4+t5+t50+t70;
t79 = in1.*t78;
t80 = in2.*t78;
t90 = t30.*t89;
t83 = -t80;
t87 = t15+t74+t79;
out1 = -t30.*t87+t56.*t61-t22.*t26.*(t6+t7-t49-t69)-(t25.*t26.*t56)./2.0;
if nargout > 1
    t88 = t14+t73+t83;
    out2 = t53.*t60+t30.*t88-(t23.*t27.*t53)./4.0+t22.*t26.*t77;
end
if nargout > 2
    et1 = in12.*(t51.*t57+t30.*t84+in9.*t26.*t53+in1.*t26.*t77-(in1.*t22.*t27.*t53)./2.0).*-2.0-in4.*(t90+t51.*t60+in9.*t26.*t77.*2.0+in1.*t26.*t88-(t23.*t27.*t51)./4.0+t22.*t26.*t84+in1.*t23.*t28.*t53.*(3.0./4.0)-(in1.*t25.*t27.*t53)./2.0-in9.*t22.*t27.*t53-in1.*t22.*t27.*t77)+in11.*(-t30.*t85+t57.*t75+in1.*t26.*(t6+t7-t49-t69)+in9.*t26.*t56-(in1.*t22.*t27.*t56)./2.0).*2.0;
    et2 = in3.*(t30.*(t78+t17.*t26+t8.*t23.*t28.*(3.0./4.0)-(t8.*t25.*t27)./2.0-in1.*in9.*t22.*t27.*2.0)+in9.*t26.*(t6+t7-t49-t69).*2.0+in1.*t26.*t87-(t23.*t27.*t75)./4.0+(t25.*t26.*t75)./2.0-t22.*t26.*t85+in1.*t23.*t28.*t56.*(3.0./4.0)-(in1.*t25.*t27.*t56)./2.0-in9.*t22.*t27.*t56-in1.*t22.*t27.*(t6+t7-t49-t69));
    out3 = et1+et2;
end
if nargout > 3
    et3 = -in3.*(t90+t40.*t61-in10.*t26.*(t6+t7-t49-t69).*2.0-in2.*t26.*t87-(t25.*t26.*t40)./2.0-t22.*t26.*t82-in2.*t23.*t28.*t56.*(3.0./4.0)+(in2.*t25.*t27.*t56)./2.0+in10.*t22.*t27.*t56+in2.*t22.*t27.*(t6+t7-t49-t69))+in4.*(t60.*t76+t30.*(t78+t18.*t26+t9.*t23.*t28.*(3.0./4.0)-(t9.*t25.*t27)./2.0-in2.*in10.*t22.*t27.*2.0)-in10.*t26.*t77.*2.0-in2.*t26.*t88-(t23.*t27.*t76)./4.0-t22.*t26.*t86-in2.*t23.*t28.*t53.*(3.0./4.0)+(in2.*t25.*t27.*t53)./2.0+in10.*t22.*t27.*t53+in2.*t22.*t27.*t77);
    et4 = in12.*(t30.*t86+in10.*t26.*t53+in2.*t26.*t77-(t22.*t26.*t76)./2.0-(in2.*t22.*t27.*t53)./2.0).*-2.0+in11.*(t40.*t57+t30.*t82+in2.*t26.*(t6+t7-t49-t69)+in10.*t26.*t56-(in2.*t22.*t27.*t56)./2.0).*2.0;
    out4 = et3+et4;
end
end

