function varargout=F_bcs_PR_segs(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=16;
   return
  case 'argrange'
   varargout{1}=struct('u',1:38);
   return
  case 'argsize'
   varargout{1}=struct('u',38);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=16;
order=varargin{1};
f=str2func(sprintf('F_bcs_PR_segs_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10,out11,out12,out13,out14,out15,out16] = F_bcs_PR_segs_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58,in59,in60,in61,in62,in63,in64,in65,in66,in67,in68,in69,in70,in71,in72,in73,in74,in75,in76)
%F_bcs_PR_segs_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15,OUT16] = F_bcs_PR_segs_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58,IN59,IN60,IN61,IN62,IN63,IN64,IN65,IN66,IN67,IN68,IN69,IN70,IN71,IN72,IN73,IN74,IN75,IN76)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Aug-2024 16:05:43

out1 = in1-in17;
if nargout > 1
    out2 = in2-in18;
end
if nargout > 2
    out3 = in5-in13;
end
if nargout > 3
    out4 = in6-in14;
end
if nargout > 4
    out5 = in25.*(in1+in2+in28-in1.^3./3.0);
end
if nargout > 5
    t2 = -in7;
    out6 = in15+t2;
end
if nargout > 6
    t3 = -in8;
    out7 = in16+t3;
end
if nargout > 7
    out8 = -in19+in3.*in33;
end
if nargout > 8
    out9 = -in20+in4.*in33;
end
if nargout > 9
    out10 = sqrt(abs(in19).^2+abs(in20).^2)-1.0;
end
if nargout > 10
    out11 = -in1+in21;
end
if nargout > 11
    out12 = -in2+in22;
end
if nargout > 12
    out13 = -in9+in11-in35.*cos(in36);
end
if nargout > 13
    out14 = -in10+in12-in35.*sin(in36);
end
if nargout > 14
    out15 = t2.*(conj(in5)-conj(in23))+t3.*(conj(in6)-conj(in24));
end
if nargout > 15
    out16 = -in34+(in5-in23).^2+(in6-in24).^2;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10,out11,out12,out13,out14,out15,out16] = F_bcs_PR_segs_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58,in59,in60,in61,in62,in63,in64,in65,in66,in67,in68,in69,in70,in71,in72,in73,in74,in75,in76)
%F_bcs_PR_segs_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15,OUT16] = F_bcs_PR_segs_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58,IN59,IN60,IN61,IN62,IN63,IN64,IN65,IN66,IN67,IN68,IN69,IN70,IN71,IN72,IN73,IN74,IN75,IN76)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Aug-2024 16:05:43

out1 = in39-in55;
if nargout > 1
    out2 = in40-in56;
end
if nargout > 2
    out3 = in43-in51;
end
if nargout > 3
    out4 = in44-in52;
end
if nargout > 4
    out5 = in63.*(in1+in2+in28-in1.^3./3.0)+in25.*(in39+in40+in66-in1.^2.*in39);
end
if nargout > 5
    out6 = -in45+in53;
end
if nargout > 6
    out7 = -in46+in54;
end
if nargout > 7
    out8 = -in57+in3.*in71+in33.*in41;
end
if nargout > 8
    out9 = -in58+in4.*in71+in33.*in42;
end
if nargout > 9
    t2 = abs(in19);
    t3 = abs(in20);
    t4 = conj(in19);
    t5 = conj(in20);
    out10 = (1.0./sqrt(t2.^2+t3.^2).*(t2.*(in57.*t4+in19.*conj(in57)).*1.0./sqrt(in19.*t4)+t3.*(in58.*t5+in20.*conj(in58)).*1.0./sqrt(in20.*t5)))./2.0;
end
if nargout > 10
    out11 = -in39+in59;
end
if nargout > 11
    out12 = -in40+in60;
end
if nargout > 12
    t6 = cos(in36);
    t7 = sin(in36);
    out13 = -in47+in49-in73.*t6+in35.*in74.*t7;
end
if nargout > 13
    out14 = -in48+in50-in73.*t7-in35.*in74.*t6;
end
if nargout > 14
    out15 = -in45.*(conj(in5)-conj(in23))-in46.*(conj(in6)-conj(in24))-in7.*(conj(in43)-conj(in61))-in8.*(conj(in44)-conj(in62));
end
if nargout > 15
    out16 = -in72+(in5-in23).*(in43-in61).*2.0+(in6-in24).*(in44-in62).*2.0;
end
end


function [out1,out2,out3,out4,out5,out6,out7,out8,out9,out10,out11,out12,out13,out14,out15,out16] = F_bcs_PR_segs_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34,in35,in36,in37,in38,in39,in40,in41,in42,in43,in44,in45,in46,in47,in48,in49,in50,in51,in52,in53,in54,in55,in56,in57,in58,in59,in60,in61,in62,in63,in64,in65,in66,in67,in68,in69,in70,in71,in72,in73,in74,in75,in76)
%F_bcs_PR_segs_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15,OUT16] = F_bcs_PR_segs_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34,IN35,IN36,IN37,IN38,IN39,IN40,IN41,IN42,IN43,IN44,IN45,IN46,IN47,IN48,IN49,IN50,IN51,IN52,IN53,IN54,IN55,IN56,IN57,IN58,IN59,IN60,IN61,IN62,IN63,IN64,IN65,IN66,IN67,IN68,IN69,IN70,IN71,IN72,IN73,IN74,IN75,IN76)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Aug-2024 16:05:43

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    out5 = in63.*(in39+in40+in66-in1.^2.*in39).*2.0-in1.*in25.*in39.^2.*2.0;
end
if nargout > 5
    out6 = 0.0;
end
if nargout > 6
    out7 = 0.0;
end
if nargout > 7
    out8 = in41.*in71.*2.0;
end
if nargout > 8
    out9 = in42.*in71.*2.0;
end
if nargout > 9
    t2 = abs(in19);
    t3 = abs(in20);
    t4 = conj(in19);
    t5 = conj(in20);
    t6 = conj(in57);
    t7 = conj(in58);
    t8 = cos(in36);
    t9 = sin(in36);
    t10 = in74.^2;
    t11 = t2.^2;
    t12 = t3.^2;
    t13 = in19.*t4;
    t14 = in20.*t5;
    t15 = in19.*t6;
    t16 = in57.*t4;
    t17 = in20.*t7;
    t18 = in58.*t5;
    t19 = t15+t16;
    t20 = t17+t18;
    t21 = t11+t12;
    t22 = 1.0./sqrt(t13);
    t23 = 1.0./sqrt(t14);
    t24 = t19.^2;
    t25 = t20.^2;
    out10 = (1.0./sqrt(t21).*((t22.^2.*t24)./2.0+(t23.^2.*t25)./2.0-(t2.*t22.^3.*t24)./2.0-(t3.*t23.^3.*t25)./2.0+in57.*t2.*t6.*t22.*2.0+in58.*t3.*t7.*t23.*2.0))./2.0-(1.0./t21.^(3.0./2.0).*(t2.*t19.*t22+t3.*t20.*t23).^2)./4.0;
end
if nargout > 10
    out11 = 0.0;
end
if nargout > 11
    out12 = 0.0;
end
if nargout > 12
    out13 = in73.*in74.*t9.*2.0+in35.*t8.*t10;
end
if nargout > 13
    out14 = in73.*in74.*t8.*-2.0+in35.*t9.*t10;
end
if nargout > 14
    out15 = in45.*(conj(in43)-conj(in61)).*-2.0-in46.*(conj(in44)-conj(in62)).*2.0;
end
if nargout > 15
    out16 = (in43-in61).^2.*2.0+(in44-in62).^2.*2.0;
end
end

