function varargout=F_fhn(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('x',1:2,'p',3:6);
   return
  case 'argsize'
   varargout{1}=struct('x',2,'p',4);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('F_fhn_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = F_fhn_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_fhn_rhs_0
%    [OUT1,OUT2] = F_fhn_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Aug-2025 11:31:13

out1 = in3.*(in1+in2+in6-in1.^3./3.0);
if nargout > 1
    out2 = -(in1-in4+in2.*in5)./in3;
end
end


function [out1,out2] = F_fhn_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_fhn_rhs_1
%    [OUT1,OUT2] = F_fhn_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Aug-2025 11:31:14

out1 = in9.*(in1+in2+in6-in1.^3./3.0)+in3.*(in7+in8+in12-in1.^2.*in7);
if nargout > 1
    out2 = -(in7-in10+in2.*in11+in5.*in8)./in3+1.0./in3.^2.*in9.*(in1-in4+in2.*in5);
end
end


function [out1,out2] = F_fhn_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%F_fhn_rhs_2
%    [OUT1,OUT2] = F_fhn_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Aug-2025 11:31:14

out1 = in9.*(in7+in8+in12-in1.^2.*in7).*2.0-in1.*in3.*in7.^2.*2.0;
if nargout > 1
    out2 = 1.0./in3.^2.*in9.*(in7-in10+in2.*in11+in5.*in8).*2.0-1.0./in3.^3.*in9.^2.*(in1-in4+in2.*in5).*2.0-(in8.*in11.*2.0)./in3;
end
end

