function varargout=F_seg1(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:16);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',12);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_seg1_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_seg1_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32)
%F_seg1_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Mar-2025 11:15:14

out1 = in5.*in9.*in12.*(in1+in2+in8-in1.^3./3.0);
if nargout > 1
    t2 = 1.0./in5;
    out2 = -in9.*in12.*t2.*(in1-in6+in2.*in7);
end
if nargout > 2
    out3 = in4.*in9.*in12.*t2+in3.*in5.*in9.*in12.*(in1.^2-1.0);
end
if nargout > 3
    out4 = -in3.*in5.*in9.*in12+in4.*in7.*in9.*in12.*t2;
end
end


function [out1,out2,out3,out4] = F_seg1_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32)
%F_seg1_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Mar-2025 11:15:14

t2 = in2.*in7;
t3 = in1.^2;
t4 = in1.^3;
t5 = -in6;
t6 = 1.0./in5;
t7 = t6.^2;
t8 = t3-1.0;
t9 = t4./3.0;
t11 = in1+t2+t5;
t10 = -t9;
t12 = in1+in2+in8+t10;
out1 = in5.*in9.*in28.*t12+in5.*in12.*in25.*t12+in9.*in12.*in21.*t12+in5.*in9.*in12.*(in17+in18+in24-in17.*t3);
if nargout > 1
    out2 = -in9.*in28.*t6.*t11-in12.*in25.*t6.*t11-in9.*in12.*t6.*(in17-in22+in2.*in23+in7.*in18)+in9.*in12.*in21.*t7.*t11;
end
if nargout > 2
    out3 = in4.*in9.*in28.*t6+in4.*in12.*in25.*t6+in9.*in12.*in20.*t6+in3.*in5.*in9.*in28.*t8+in3.*in5.*in12.*in25.*t8+in3.*in9.*in12.*in21.*t8-in4.*in9.*in12.*in21.*t7+in5.*in9.*in12.*in19.*t8+in1.*in3.*in5.*in9.*in12.*in17.*2.0;
end
if nargout > 3
    out4 = -in3.*in5.*in9.*in28-in3.*in5.*in12.*in25-in3.*in9.*in12.*in21-in5.*in9.*in12.*in19+in4.*in7.*in9.*in28.*t6+in4.*in7.*in12.*in25.*t6+in4.*in9.*in12.*in23.*t6+in7.*in9.*in12.*in20.*t6-in4.*in7.*in9.*in12.*in21.*t7;
end
end


function [out1,out2,out3,out4] = F_seg1_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32)
%F_seg1_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_seg1_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Mar-2025 11:15:15

t2 = in2.*in7;
t3 = in2.*in23;
t4 = in7.*in18;
t5 = in1.^2;
t6 = in1.^3;
t7 = in17.^2;
t8 = in21.^2;
t9 = -in6;
t10 = -in22;
t11 = 1.0./in5;
t12 = t11.^2;
t13 = t11.^3;
t14 = in17.*t5;
t15 = t5-1.0;
t16 = t6./3.0;
t19 = in1+t2+t9;
t22 = in17+t3+t4+t10;
t17 = -t14;
t18 = -t16;
t20 = in17+in18+in24+t17;
t21 = in1+in2+in8+t18;
out1 = in5.*in9.*in28.*t20.*2.0+in5.*in12.*in25.*t20.*2.0+in9.*in12.*in21.*t20.*2.0+in5.*in25.*in28.*t21.*2.0+in9.*in21.*in28.*t21.*2.0+in12.*in21.*in25.*t21.*2.0-in1.*in5.*in9.*in12.*t7.*2.0;
if nargout > 1
    out2 = in9.*in28.*t11.*t22.*-2.0-in12.*in25.*t11.*t22.*2.0-in25.*in28.*t11.*t19.*2.0-in9.*in12.*in18.*in23.*t11.*2.0+in9.*in12.*in21.*t12.*t22.*2.0+in9.*in21.*in28.*t12.*t19.*2.0+in12.*in21.*in25.*t12.*t19.*2.0-in9.*in12.*t8.*t13.*t19.*2.0;
end
if nargout > 2
    out3 = in4.*in25.*in28.*t11.*2.0+in9.*in20.*in28.*t11.*2.0+in12.*in20.*in25.*t11.*2.0+in3.*in5.*in9.*in12.*t7.*2.0-in4.*in9.*in21.*in28.*t12.*2.0-in4.*in12.*in21.*in25.*t12.*2.0-in9.*in12.*in20.*in21.*t12.*2.0+in3.*in5.*in25.*in28.*t15.*2.0+in3.*in9.*in21.*in28.*t15.*2.0+in3.*in12.*in21.*in25.*t15.*2.0+in5.*in9.*in19.*in28.*t15.*2.0+in5.*in12.*in19.*in25.*t15.*2.0+in9.*in12.*in19.*in21.*t15.*2.0+in4.*in9.*in12.*t8.*t13.*2.0+in1.*in3.*in5.*in9.*in17.*in28.*4.0+in1.*in3.*in5.*in12.*in17.*in25.*4.0+in1.*in3.*in9.*in12.*in17.*in21.*4.0+in1.*in5.*in9.*in12.*in17.*in19.*4.0;
end
if nargout > 3
    out4 = in3.*in5.*in25.*in28.*-2.0-in3.*in9.*in21.*in28.*2.0-in3.*in12.*in21.*in25.*2.0-in5.*in9.*in19.*in28.*2.0-in5.*in12.*in19.*in25.*2.0-in9.*in12.*in19.*in21.*2.0+in4.*in7.*in25.*in28.*t11.*2.0+in4.*in9.*in23.*in28.*t11.*2.0+in4.*in12.*in23.*in25.*t11.*2.0+in7.*in9.*in20.*in28.*t11.*2.0+in7.*in12.*in20.*in25.*t11.*2.0+in9.*in12.*in20.*in23.*t11.*2.0-in4.*in7.*in9.*in21.*in28.*t12.*2.0-in4.*in7.*in12.*in21.*in25.*t12.*2.0-in4.*in9.*in12.*in21.*in23.*t12.*2.0-in7.*in9.*in12.*in20.*in21.*t12.*2.0+in4.*in7.*in9.*in12.*t8.*t13.*2.0;
end
end

