function varargout=F_seg2(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:15);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',11);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_seg2_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_seg2_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30)
%F_seg2_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 15:46:30

t2 = in11-1.0;
out1 = -in5.*t2.*(in1+in2+in8-in1.^3./3.0);
if nargout > 1
    t3 = 1.0./in5;
    out2 = t2.*t3.*(in1-in6+in2.*in7);
end
if nargout > 2
    out3 = -in4.*t2.*t3-in3.*in5.*t2.*(in1.^2-1.0);
end
if nargout > 3
    out4 = in3.*in5.*t2-in4.*in7.*t2.*t3;
end
end


function [out1,out2,out3,out4] = F_seg2_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30)
%F_seg2_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 15:46:30

t2 = in2.*in7;
t3 = in1.^2;
t4 = in1.^3;
t5 = -in6;
t6 = in11-1.0;
t7 = 1.0./in5;
t8 = t7.^2;
t9 = t3-1.0;
t10 = t4./3.0;
t12 = in1+t2+t5;
t11 = -t10;
t13 = in1+in2+in8+t11;
out1 = -in5.*t6.*(in16+in17+in23-in16.*t3)-in5.*in26.*t13-in20.*t6.*t13;
if nargout > 1
    out2 = t6.*t7.*(in16-in21+in2.*in22+in7.*in17)+in26.*t7.*t12-in20.*t6.*t8.*t12;
end
if nargout > 2
    out3 = -in4.*in26.*t7-in19.*t6.*t7-in3.*in5.*in26.*t9-in3.*in20.*t6.*t9+in4.*in20.*t6.*t8-in5.*in18.*t6.*t9-in1.*in3.*in5.*in16.*t6.*2.0;
end
if nargout > 3
    out4 = in3.*in5.*in26+in3.*in20.*t6+in5.*in18.*t6-in4.*in7.*in26.*t7-in4.*in22.*t6.*t7-in7.*in19.*t6.*t7+in4.*in7.*in20.*t6.*t8;
end
end


function [out1,out2,out3,out4] = F_seg2_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30)
%F_seg2_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_seg2_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 15:46:30

t2 = in2.*in7;
t3 = in2.*in22;
t4 = in7.*in17;
t5 = in1.^2;
t6 = in16.^2;
t7 = in20.^2;
t8 = -in6;
t9 = -in21;
t10 = in11-1.0;
t11 = 1.0./in5;
t12 = t11.^2;
t13 = t11.^3;
t14 = in16.*t5;
t15 = t5-1.0;
t17 = in1+t2+t8;
t19 = in16+t3+t4+t9;
t16 = -t14;
t18 = in16+in17+in23+t16;
out1 = in5.*in26.*t18.*-2.0-in20.*t10.*t18.*2.0-in20.*in26.*(in1+in2+in8-in1.^3./3.0).*2.0+in1.*in5.*t6.*t10.*2.0;
if nargout > 1
    out2 = in26.*t11.*t19.*2.0+in17.*in22.*t10.*t11.*2.0-in20.*in26.*t12.*t17.*2.0-in20.*t10.*t12.*t19.*2.0+t7.*t10.*t13.*t17.*2.0;
end
if nargout > 2
    out3 = in19.*in26.*t11.*-2.0+in4.*in20.*in26.*t12.*2.0-in3.*in20.*in26.*t15.*2.0-in5.*in18.*in26.*t15.*2.0-in3.*in5.*t6.*t10.*2.0+in19.*in20.*t10.*t12.*2.0-in18.*in20.*t10.*t15.*2.0-in4.*t7.*t10.*t13.*2.0-in1.*in3.*in5.*in16.*in26.*4.0-in1.*in3.*in16.*in20.*t10.*4.0-in1.*in5.*in16.*in18.*t10.*4.0;
end
if nargout > 3
    out4 = in3.*in20.*in26.*2.0+in5.*in18.*in26.*2.0+in18.*in20.*t10.*2.0-in4.*in22.*in26.*t11.*2.0-in7.*in19.*in26.*t11.*2.0-in19.*in22.*t10.*t11.*2.0+in4.*in7.*in20.*in26.*t12.*2.0+in4.*in20.*in22.*t10.*t12.*2.0+in7.*in19.*in20.*t10.*t12.*2.0-in4.*in7.*t7.*t10.*t13.*2.0;
end
end

