function varargout=F_VAR(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('x',1:4,'p',5:10);
   return
  case 'argsize'
   varargout{1}=struct('x',4,'p',6);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('F_VAR_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = F_VAR_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%F_VAR_rhs_0
%    [OUT1,OUT2,OUT3,OUT4] = F_VAR_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-Oct-2025 15:19:57

out1 = in5.*(in1+in2+in8-in1.^3./3.0);
if nargout > 1
    t2 = 1.0./in5;
    out2 = -t2.*(in1-in6+in2.*in7);
end
if nargout > 2
    out3 = in4.*t2+in3.*in5.*(in1.^2-1.0);
end
if nargout > 3
    out4 = -in3.*in5+in4.*in7.*t2;
end
end


function [out1,out2,out3,out4] = F_VAR_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%F_VAR_rhs_1
%    [OUT1,OUT2,OUT3,OUT4] = F_VAR_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-Oct-2025 15:19:57

t2 = in1.^2;
out1 = in15.*(in1+in2+in8-in1.^3./3.0)+in5.*(in11+in12+in18-in11.*t2);
if nargout > 1
    t3 = 1.0./in5;
    t4 = t3.^2;
    out2 = -t3.*(in11-in16+in2.*in17+in7.*in12)+in15.*t4.*(in1-in6+in2.*in7);
end
if nargout > 2
    t5 = t2-1.0;
    out3 = in14.*t3+in3.*in15.*t5-in4.*in15.*t4+in5.*in13.*t5+in1.*in3.*in5.*in11.*2.0;
end
if nargout > 3
    out4 = -in3.*in15-in5.*in13+in4.*in17.*t3+in7.*in14.*t3-in4.*in7.*in15.*t4;
end
end


function [out1,out2,out3,out4] = F_VAR_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%F_VAR_rhs_2
%    [OUT1,OUT2,OUT3,OUT4] = F_VAR_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-Oct-2025 15:19:57

t2 = in1.^2;
t3 = in11.^2;
out1 = in15.*(in11+in12+in18-in11.*t2).*2.0-in1.*in5.*t3.*2.0;
if nargout > 1
    t4 = in15.^2;
    t5 = 1.0./in5;
    t6 = t5.^2;
    t7 = t5.^3;
    out2 = t4.*t7.*(in1-in6+in2.*in7).*-2.0+in15.*t6.*(in11-in16+in2.*in17+in7.*in12).*2.0-in12.*in17.*t5.*2.0;
end
if nargout > 2
    out3 = in13.*in15.*(t2-1.0).*2.0+in3.*in5.*t3.*2.0-in14.*in15.*t6.*2.0+in4.*t4.*t7.*2.0+in1.*in3.*in11.*in15.*4.0+in1.*in5.*in11.*in13.*4.0;
end
if nargout > 3
    out4 = in13.*in15.*-2.0+in14.*in17.*t5.*2.0-in4.*in15.*in17.*t6.*2.0-in7.*in14.*in15.*t6.*2.0+in4.*in7.*t4.*t7.*2.0;
end
end

